// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BlobstoreCompact) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LicenseExpirationNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MalwareRemediator) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepairCreateBrowseNodes) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryDockerGc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryDockerUploadPurge) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryMavenRemoveSnapshots) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RepositoryPurgeUnused) Hub() {}
