// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RepositoryMavenRemoveSnapshotsFrequencyInitParameters struct {

	// (String) Cron expression for the task. Only applies for for "cron" schedule.
	// Cron expression for the task. Only applies for for "cron" schedule.
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	// (List of Number) Array with the number of the days the task must run.
	// Array with the number of the days the task must run.
	//
	// - For "weekly" schedule allowed values, 1 to 7.
	// - For "monthly" schedule allowed values, 1 to 31.
	RecurringDays []*float64 `json:"recurringDays,omitempty" tf:"recurring_days,omitempty"`

	// (String) Type of Schedule.
	// Type of Schedule.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// 04-26 01:30 UTC). Does not apply for "manual" schedule.
	// Start date of the task represented in unix timestamp. Sonatype Nexus Repository persists this in milliseconds, so values for any modern date are 13 digits (e.g. `1777167000000` for 2026-04-26 01:30 UTC). Does not apply for "manual" schedule.
	StartDate *float64 `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// 05:00
	// The offset time zone of the client. Example: -05:00
	TimezoneOffset *string `json:"timezoneOffset,omitempty" tf:"timezone_offset,omitempty"`
}

type RepositoryMavenRemoveSnapshotsFrequencyObservation struct {

	// (String) Cron expression for the task. Only applies for for "cron" schedule.
	// Cron expression for the task. Only applies for for "cron" schedule.
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	// (List of Number) Array with the number of the days the task must run.
	// Array with the number of the days the task must run.
	//
	// - For "weekly" schedule allowed values, 1 to 7.
	// - For "monthly" schedule allowed values, 1 to 31.
	RecurringDays []*float64 `json:"recurringDays,omitempty" tf:"recurring_days,omitempty"`

	// (String) Type of Schedule.
	// Type of Schedule.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// 04-26 01:30 UTC). Does not apply for "manual" schedule.
	// Start date of the task represented in unix timestamp. Sonatype Nexus Repository persists this in milliseconds, so values for any modern date are 13 digits (e.g. `1777167000000` for 2026-04-26 01:30 UTC). Does not apply for "manual" schedule.
	StartDate *float64 `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// 05:00
	// The offset time zone of the client. Example: -05:00
	TimezoneOffset *string `json:"timezoneOffset,omitempty" tf:"timezone_offset,omitempty"`
}

type RepositoryMavenRemoveSnapshotsFrequencyParameters struct {

	// (String) Cron expression for the task. Only applies for for "cron" schedule.
	// Cron expression for the task. Only applies for for "cron" schedule.
	// +kubebuilder:validation:Optional
	CronExpression *string `json:"cronExpression,omitempty" tf:"cron_expression,omitempty"`

	// (List of Number) Array with the number of the days the task must run.
	// Array with the number of the days the task must run.
	//
	// - For "weekly" schedule allowed values, 1 to 7.
	// - For "monthly" schedule allowed values, 1 to 31.
	// +kubebuilder:validation:Optional
	RecurringDays []*float64 `json:"recurringDays,omitempty" tf:"recurring_days,omitempty"`

	// (String) Type of Schedule.
	// Type of Schedule.
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule" tf:"schedule,omitempty"`

	// 04-26 01:30 UTC). Does not apply for "manual" schedule.
	// Start date of the task represented in unix timestamp. Sonatype Nexus Repository persists this in milliseconds, so values for any modern date are 13 digits (e.g. `1777167000000` for 2026-04-26 01:30 UTC). Does not apply for "manual" schedule.
	// +kubebuilder:validation:Optional
	StartDate *float64 `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// 05:00
	// The offset time zone of the client. Example: -05:00
	// +kubebuilder:validation:Optional
	TimezoneOffset *string `json:"timezoneOffset,omitempty" tf:"timezone_offset,omitempty"`
}

type RepositoryMavenRemoveSnapshotsInitParameters struct {

	// mail address for task notifications.
	// E-mail address for task notifications.
	AlertEmail *string `json:"alertEmail,omitempty" tf:"alert_email,omitempty"`

	// (Boolean) Indicates if the task is enabled.
	// Indicates if the task is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Frequency Schedule for this Task. (see below for nested schema)
	Frequency *RepositoryMavenRemoveSnapshotsFrequencyInitParameters `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) The name of the Task.
	// The name of the Task.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The type of Task.
	// The type of Task.
	NotificationCondition *string `json:"notificationCondition,omitempty" tf:"notification_condition,omitempty"`

	// (Attributes) Properties specific to this Task type (see below for nested schema)
	Properties *RepositoryMavenRemoveSnapshotsPropertiesInitParameters `json:"properties,omitempty" tf:"properties,omitempty"`
}

type RepositoryMavenRemoveSnapshotsObservation struct {

	// mail address for task notifications.
	// E-mail address for task notifications.
	AlertEmail *string `json:"alertEmail,omitempty" tf:"alert_email,omitempty"`

	// (Boolean) Indicates if the task is enabled.
	// Indicates if the task is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Frequency Schedule for this Task. (see below for nested schema)
	Frequency *RepositoryMavenRemoveSnapshotsFrequencyObservation `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) The internal ID of the Task.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The name of the Task.
	// The name of the Task.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The type of Task.
	// The type of Task.
	NotificationCondition *string `json:"notificationCondition,omitempty" tf:"notification_condition,omitempty"`

	// (Attributes) Properties specific to this Task type (see below for nested schema)
	Properties *RepositoryMavenRemoveSnapshotsPropertiesObservation `json:"properties,omitempty" tf:"properties,omitempty"`
}

type RepositoryMavenRemoveSnapshotsParameters struct {

	// mail address for task notifications.
	// E-mail address for task notifications.
	// +kubebuilder:validation:Optional
	AlertEmail *string `json:"alertEmail,omitempty" tf:"alert_email,omitempty"`

	// (Boolean) Indicates if the task is enabled.
	// Indicates if the task is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Frequency Schedule for this Task. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Frequency *RepositoryMavenRemoveSnapshotsFrequencyParameters `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// (String) The name of the Task.
	// The name of the Task.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The type of Task.
	// The type of Task.
	// +kubebuilder:validation:Optional
	NotificationCondition *string `json:"notificationCondition,omitempty" tf:"notification_condition,omitempty"`

	// (Attributes) Properties specific to this Task type (see below for nested schema)
	// +kubebuilder:validation:Optional
	Properties *RepositoryMavenRemoveSnapshotsPropertiesParameters `json:"properties,omitempty" tf:"properties,omitempty"`
}

type RepositoryMavenRemoveSnapshotsPropertiesInitParameters struct {

	// (Number) The grace period during which snapshots with an associated release will not be deleted.
	// The grace period during which snapshots with an associated release will not be deleted.
	GracePeriodInDays *float64 `json:"gracePeriodInDays,omitempty" tf:"grace_period_in_days,omitempty"`

	// (Number) Minimum number of snapshots to keep for one GAV.
	// Minimum number of snapshots to keep for one GAV.
	MinimumRetained *float64 `json:"minimumRetained,omitempty" tf:"minimum_retained,omitempty"`

	// (Boolean) Delete all snapshots that have a corresponding release.
	// Delete all snapshots that have a corresponding release.
	RemoveIfReleased *bool `json:"removeIfReleased,omitempty" tf:"remove_if_released,omitempty"`

	// (String) The Maven repository or repository group to remove snapshots from.
	// The Maven repository or repository group to remove snapshots from.
	RepositoryName *string `json:"repositoryName,omitempty" tf:"repository_name,omitempty"`

	// (Number) Delete all snapshots older than this, provided we still keep the minimum number specified.
	// Delete all snapshots older than this, provided we still keep the minimum number specified.
	SnapshotRetentionDays *float64 `json:"snapshotRetentionDays,omitempty" tf:"snapshot_retention_days,omitempty"`
}

type RepositoryMavenRemoveSnapshotsPropertiesObservation struct {

	// (Number) The grace period during which snapshots with an associated release will not be deleted.
	// The grace period during which snapshots with an associated release will not be deleted.
	GracePeriodInDays *float64 `json:"gracePeriodInDays,omitempty" tf:"grace_period_in_days,omitempty"`

	// (Number) Minimum number of snapshots to keep for one GAV.
	// Minimum number of snapshots to keep for one GAV.
	MinimumRetained *float64 `json:"minimumRetained,omitempty" tf:"minimum_retained,omitempty"`

	// (Boolean) Delete all snapshots that have a corresponding release.
	// Delete all snapshots that have a corresponding release.
	RemoveIfReleased *bool `json:"removeIfReleased,omitempty" tf:"remove_if_released,omitempty"`

	// (String) The Maven repository or repository group to remove snapshots from.
	// The Maven repository or repository group to remove snapshots from.
	RepositoryName *string `json:"repositoryName,omitempty" tf:"repository_name,omitempty"`

	// (Number) Delete all snapshots older than this, provided we still keep the minimum number specified.
	// Delete all snapshots older than this, provided we still keep the minimum number specified.
	SnapshotRetentionDays *float64 `json:"snapshotRetentionDays,omitempty" tf:"snapshot_retention_days,omitempty"`
}

type RepositoryMavenRemoveSnapshotsPropertiesParameters struct {

	// (Number) The grace period during which snapshots with an associated release will not be deleted.
	// The grace period during which snapshots with an associated release will not be deleted.
	// +kubebuilder:validation:Optional
	GracePeriodInDays *float64 `json:"gracePeriodInDays,omitempty" tf:"grace_period_in_days,omitempty"`

	// (Number) Minimum number of snapshots to keep for one GAV.
	// Minimum number of snapshots to keep for one GAV.
	// +kubebuilder:validation:Optional
	MinimumRetained *float64 `json:"minimumRetained,omitempty" tf:"minimum_retained,omitempty"`

	// (Boolean) Delete all snapshots that have a corresponding release.
	// Delete all snapshots that have a corresponding release.
	// +kubebuilder:validation:Optional
	RemoveIfReleased *bool `json:"removeIfReleased,omitempty" tf:"remove_if_released,omitempty"`

	// (String) The Maven repository or repository group to remove snapshots from.
	// The Maven repository or repository group to remove snapshots from.
	// +kubebuilder:validation:Optional
	RepositoryName *string `json:"repositoryName" tf:"repository_name,omitempty"`

	// (Number) Delete all snapshots older than this, provided we still keep the minimum number specified.
	// Delete all snapshots older than this, provided we still keep the minimum number specified.
	// +kubebuilder:validation:Optional
	SnapshotRetentionDays *float64 `json:"snapshotRetentionDays,omitempty" tf:"snapshot_retention_days,omitempty"`
}

// RepositoryMavenRemoveSnapshotsSpec defines the desired state of RepositoryMavenRemoveSnapshots
type RepositoryMavenRemoveSnapshotsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RepositoryMavenRemoveSnapshotsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryMavenRemoveSnapshotsInitParameters `json:"initProvider,omitempty"`
}

// RepositoryMavenRemoveSnapshotsStatus defines the observed state of RepositoryMavenRemoveSnapshots.
type RepositoryMavenRemoveSnapshotsStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryMavenRemoveSnapshotsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryMavenRemoveSnapshots is the Schema for the RepositoryMavenRemoveSnapshotss API. Manage Task 'Maven - Delete SNAPSHOT' (repository.maven.remove-snapshots)
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,sonatyperepo}
type RepositoryMavenRemoveSnapshots struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.frequency) || (has(self.initProvider) && has(self.initProvider.frequency))",message="spec.forProvider.frequency is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notificationCondition) || (has(self.initProvider) && has(self.initProvider.notificationCondition))",message="spec.forProvider.notificationCondition is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.properties) || (has(self.initProvider) && has(self.initProvider.properties))",message="spec.forProvider.properties is a required parameter"
	Spec   RepositoryMavenRemoveSnapshotsSpec   `json:"spec"`
	Status RepositoryMavenRemoveSnapshotsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryMavenRemoveSnapshotsList contains a list of RepositoryMavenRemoveSnapshotss
type RepositoryMavenRemoveSnapshotsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryMavenRemoveSnapshots `json:"items"`
}

// Repository type metadata.
var (
	RepositoryMavenRemoveSnapshots_Kind             = "RepositoryMavenRemoveSnapshots"
	RepositoryMavenRemoveSnapshots_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryMavenRemoveSnapshots_Kind}.String()
	RepositoryMavenRemoveSnapshots_KindAPIVersion   = RepositoryMavenRemoveSnapshots_Kind + "." + CRDGroupVersion.String()
	RepositoryMavenRemoveSnapshots_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryMavenRemoveSnapshots_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryMavenRemoveSnapshots{}, &RepositoryMavenRemoveSnapshotsList{})
}
