apiVersion: repository.nexus.m.tinyorbit.vn/v1alpha1
kind: AnsiblegalaxyProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/ansiblegalaxyproxy
  labels:
    testing.upbound.io/example-name: ansiblegalaxy_proxy
  name: ansiblegalaxy-proxy
  namespace: crossplane-system
spec:
  forProvider:
    httpClient:
      autoBlock: false
      blocked: false
      connection:
        enableCircularRedirects: true
        enableCookies: true
        retries: 3
        timeout: 60
        useTrustStore: false
    negativeCache:
      enabled: true
      timeToLive: 1440
    online: true
    proxy:
      contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://galaxy.ansible.com
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
