apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: CargoHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/cargohosted
  labels:
    testing.upbound.io/example-name: cargo_hosted
  name: cargo-hosted
spec:
  forProvider:
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
      writePolicy: ALLOW
