apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: CondaProxy
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/condaproxy
  labels:
    testing.upbound.io/example-name: conda_proxy
  name: conda-proxy
spec:
  forProvider:
    httpClient:
      autoBlock: false
      blocked: false
      connection:
        enableCircularRedirects: true
        enableCookies: true
        retries: 0
        timeout: 60
        useTrustStore: false
    negativeCache:
      enabled: true
      timeToLive: 1440
    online: true
    proxy:
      contentMaxAge: 1440
      metadataMaxAge: 1440
      remoteUrl: https://conda.anaconda.org/conda-forge/
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
