apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: Maven2Hosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/maven2hosted
  labels:
    testing.upbound.io/example-name: maven_hosted
  name: maven-hosted
spec:
  forProvider:
    maven:
      layoutPolicy: STRICT
      versionPolicy: RELEASE
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
