apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: NugetHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/nugethosted
  labels:
    testing.upbound.io/example-name: nuget_hosted
  name: nuget-hosted
spec:
  forProvider:
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
