apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: OciHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/ocihosted
  labels:
    testing.upbound.io/example-name: oci_hosted
  name: oci-hosted
spec:
  forProvider:
    cosign:
      enforcement: NONE
    oci:
      forceBasicAuth: true
      httpPort: 8082
      v1Enabled: false
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: true
      writePolicy: ALLOW
