apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: RawGroup
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/rawgroup
  labels:
    testing.upbound.io/example-name: raw_group
  name: raw-group
spec:
  forProvider:
    group:
      member_repositories:
      - raw-proxy-repo
      - raw-hosted-repo
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
