apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: RGroup
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/rgroup
  labels:
    testing.upbound.io/example-name: r_group
  name: r-group
spec:
  forProvider:
    group:
      member_repositories:
      - r-proxy-repo
      - r-hosted-repo
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
