apiVersion: repository.nexus.tinyorbit.vn/v1alpha1
kind: RubygemsHosted
metadata:
  annotations:
    meta.upbound.io/example-id: repository/v1alpha1/rubygemshosted
  labels:
    testing.upbound.io/example-name: rubygems_hosted
  name: rubygems-hosted
spec:
  forProvider:
    online: true
    storage:
      blobStoreName: default
      strictContentTypeValidation: false
      writePolicy: ALLOW
