apiVersion: system.nexus.m.tinyorbit.vn/v1alpha1
kind: ConfigMail
metadata:
  annotations:
    meta.upbound.io/example-id: system/v1alpha1/configmail
  labels:
    testing.upbound.io/example-name: mail_config
  name: mail-config
  namespace: crossplane-system
spec:
  forProvider:
    enabled: true
    fromAddress: nexus@example.com
    host: smtp.example.com
    nexusTrustStoreEnabled: false
    passwordSecretRef:
      key: example-key
      name: example-secret
    port: 587
    sslOnConnectEnabled: false
    sslServerIdentityCheckEnabled: true
    startTlsEnabled: true
    startTlsRequired: false
    subjectPrefix: '[Nexus]'
    username: nexus-user
