apiVersion: security.nexus.m.tinyorbit.vn/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: security/v1alpha1/role
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: Administrator role
    name: nx-admin
    privileges:
    - nx-all
