// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NpmGroupCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type NpmGroupCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type NpmGroupCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type NpmGroupGroupInitParameters struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`

	// (String) This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	// This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	WritableMember *string `json:"writableMember,omitempty" tf:"writable_member,omitempty"`
}

type NpmGroupGroupObservation struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`

	// (String) This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	// This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	WritableMember *string `json:"writableMember,omitempty" tf:"writable_member,omitempty"`
}

type NpmGroupGroupParameters struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	// +kubebuilder:validation:Optional
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`

	// (String) This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	// This field is for the Group Deployment feature available in Sonatype Nexus Repository Pro.
	// +kubebuilder:validation:Optional
	WritableMember *string `json:"writableMember,omitempty" tf:"writable_member,omitempty"`
}

type NpmGroupInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *NpmGroupCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	Group *NpmGroupGroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *NpmGroupStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type NpmGroupObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *NpmGroupCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	Group *NpmGroupGroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *NpmGroupStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type NpmGroupParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *NpmGroupCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Group *NpmGroupGroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *NpmGroupStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type NpmGroupStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type NpmGroupStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type NpmGroupStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`
}

// NpmGroupSpec defines the desired state of NpmGroup
type NpmGroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NpmGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NpmGroupInitParameters `json:"initProvider,omitempty"`
}

// NpmGroupStatus defines the observed state of NpmGroup.
type NpmGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NpmGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NpmGroup is the Schema for the NpmGroups API. Manage Group NPM Repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type NpmGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.group) || (has(self.initProvider) && has(self.initProvider.group))",message="spec.forProvider.group is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   NpmGroupSpec   `json:"spec"`
	Status NpmGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NpmGroupList contains a list of NpmGroups
type NpmGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NpmGroup `json:"items"`
}

// Repository type metadata.
var (
	NpmGroup_Kind             = "NpmGroup"
	NpmGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NpmGroup_Kind}.String()
	NpmGroup_KindAPIVersion   = NpmGroup_Kind + "." + CRDGroupVersion.String()
	NpmGroup_GroupVersionKind = CRDGroupVersion.WithKind(NpmGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&NpmGroup{}, &NpmGroupList{})
}
