// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RubygemsLegacyProxyCleanupInitParameters struct {

	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RubygemsLegacyProxyCleanupObservation struct {

	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RubygemsLegacyProxyCleanupParameters struct {

	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RubygemsLegacyProxyHTTPClientAuthenticationInitParameters struct {

	// Bearer Token used when Authentication Type == bearerToken
	BearerTokenSecretRef *v2.SecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// NTLM Domain
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// NTLM Host
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// Password
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// Authentication type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RubygemsLegacyProxyHTTPClientAuthenticationObservation struct {

	// NTLM Domain
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// NTLM Host
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// Authentication type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RubygemsLegacyProxyHTTPClientAuthenticationParameters struct {

	// Bearer Token used when Authentication Type == bearerToken
	// +kubebuilder:validation:Optional
	BearerTokenSecretRef *v2.SecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// NTLM Domain
	// +kubebuilder:validation:Optional
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// NTLM Host
	// +kubebuilder:validation:Optional
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// Password
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	// +kubebuilder:validation:Optional
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// Authentication type
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Username
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type RubygemsLegacyProxyHTTPClientConnectionInitParameters struct {

	// Whether to enable redirects to the same location (may be required by some servers)
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// Whether to allow cookies to be stored and used
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// Total retries if the initial connection attempt suffers a timeout
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Custom fragment to append to User-Agent header in HTTP requests
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type RubygemsLegacyProxyHTTPClientConnectionObservation struct {

	// Whether to enable redirects to the same location (may be required by some servers)
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// Whether to allow cookies to be stored and used
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// Total retries if the initial connection attempt suffers a timeout
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Custom fragment to append to User-Agent header in HTTP requests
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type RubygemsLegacyProxyHTTPClientConnectionParameters struct {

	// Whether to enable redirects to the same location (may be required by some servers)
	// +kubebuilder:validation:Optional
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// Whether to allow cookies to be stored and used
	// +kubebuilder:validation:Optional
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// Total retries if the initial connection attempt suffers a timeout
	// +kubebuilder:validation:Optional
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	// +kubebuilder:validation:Optional
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Custom fragment to append to User-Agent header in HTTP requests
	// +kubebuilder:validation:Optional
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type RubygemsLegacyProxyHTTPClientInitParameters struct {
	Authentication *RubygemsLegacyProxyHTTPClientAuthenticationInitParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	AutoBlock *bool `json:"autoBlock,omitempty" tf:"auto_block,omitempty"`

	// Whether to block outbound connections on the repository
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	Connection *RubygemsLegacyProxyHTTPClientConnectionInitParameters `json:"connection,omitempty" tf:"connection,omitempty"`
}

type RubygemsLegacyProxyHTTPClientObservation struct {
	Authentication *RubygemsLegacyProxyHTTPClientAuthenticationObservation `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	AutoBlock *bool `json:"autoBlock,omitempty" tf:"auto_block,omitempty"`

	// Whether to block outbound connections on the repository
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	Connection *RubygemsLegacyProxyHTTPClientConnectionObservation `json:"connection,omitempty" tf:"connection,omitempty"`
}

type RubygemsLegacyProxyHTTPClientParameters struct {

	// +kubebuilder:validation:Optional
	Authentication *RubygemsLegacyProxyHTTPClientAuthenticationParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	// +kubebuilder:validation:Optional
	AutoBlock *bool `json:"autoBlock" tf:"auto_block,omitempty"`

	// Whether to block outbound connections on the repository
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked" tf:"blocked,omitempty"`

	// +kubebuilder:validation:Optional
	Connection *RubygemsLegacyProxyHTTPClientConnectionParameters `json:"connection,omitempty" tf:"connection,omitempty"`
}

type RubygemsLegacyProxyInitParameters struct {
	Cleanup *RubygemsLegacyProxyCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	HTTPClient *RubygemsLegacyProxyHTTPClientInitParameters `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	NegativeCache *RubygemsLegacyProxyNegativeCacheInitParameters `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	Proxy *RubygemsLegacyProxyProxyInitParameters `json:"proxy,omitempty" tf:"proxy,omitempty"`

	Replication *RubygemsLegacyProxyReplicationInitParameters `json:"replication,omitempty" tf:"replication,omitempty"`

	RepositoryFirewall *RubygemsLegacyProxyRepositoryFirewallInitParameters `json:"repositoryFirewall,omitempty" tf:"repository_firewall,omitempty"`

	// Routing Rule
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	Storage *RubygemsLegacyProxyStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RubygemsLegacyProxyNegativeCacheInitParameters struct {

	// Whether to cache responses for content not present in the proxied repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How long to cache the fact that a file was not found in the repository (in minutes)
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type RubygemsLegacyProxyNegativeCacheObservation struct {

	// Whether to cache responses for content not present in the proxied repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How long to cache the fact that a file was not found in the repository (in minutes)
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type RubygemsLegacyProxyNegativeCacheParameters struct {

	// Whether to cache responses for content not present in the proxied repository
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How long to cache the fact that a file was not found in the repository (in minutes)
	// +kubebuilder:validation:Optional
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type RubygemsLegacyProxyObservation struct {
	Cleanup *RubygemsLegacyProxyCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	HTTPClient *RubygemsLegacyProxyHTTPClientObservation `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	NegativeCache *RubygemsLegacyProxyNegativeCacheObservation `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	Proxy *RubygemsLegacyProxyProxyObservation `json:"proxy,omitempty" tf:"proxy,omitempty"`

	Replication *RubygemsLegacyProxyReplicationObservation `json:"replication,omitempty" tf:"replication,omitempty"`

	RepositoryFirewall *RubygemsLegacyProxyRepositoryFirewallObservation `json:"repositoryFirewall,omitempty" tf:"repository_firewall,omitempty"`

	// Routing Rule
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	Storage *RubygemsLegacyProxyStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RubygemsLegacyProxyParameters struct {

	// +kubebuilder:validation:Optional
	Cleanup *RubygemsLegacyProxyCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// +kubebuilder:validation:Optional
	HTTPClient *RubygemsLegacyProxyHTTPClientParameters `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	// +kubebuilder:validation:Optional
	NegativeCache *RubygemsLegacyProxyNegativeCacheParameters `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// +kubebuilder:validation:Optional
	Proxy *RubygemsLegacyProxyProxyParameters `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// +kubebuilder:validation:Optional
	Replication *RubygemsLegacyProxyReplicationParameters `json:"replication,omitempty" tf:"replication,omitempty"`

	// +kubebuilder:validation:Optional
	RepositoryFirewall *RubygemsLegacyProxyRepositoryFirewallParameters `json:"repositoryFirewall,omitempty" tf:"repository_firewall,omitempty"`

	// Routing Rule
	// +kubebuilder:validation:Optional
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	// +kubebuilder:validation:Optional
	Storage *RubygemsLegacyProxyStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RubygemsLegacyProxyProxyInitParameters struct {

	// How long to cache artifacts before rechecking the remote repository (in minutes)
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// How long to cache metadata before rechecking the remote repository (in minutes)
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// Location of the remote repository being proxied
	RemoteURL *string `json:"remoteUrl,omitempty" tf:"remote_url,omitempty"`
}

type RubygemsLegacyProxyProxyObservation struct {

	// How long to cache artifacts before rechecking the remote repository (in minutes)
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// How long to cache metadata before rechecking the remote repository (in minutes)
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// Location of the remote repository being proxied
	RemoteURL *string `json:"remoteUrl,omitempty" tf:"remote_url,omitempty"`
}

type RubygemsLegacyProxyProxyParameters struct {

	// How long to cache artifacts before rechecking the remote repository (in minutes)
	// +kubebuilder:validation:Optional
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// How long to cache metadata before rechecking the remote repository (in minutes)
	// +kubebuilder:validation:Optional
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// Location of the remote repository being proxied
	// +kubebuilder:validation:Optional
	RemoteURL *string `json:"remoteUrl" tf:"remote_url,omitempty"`
}

type RubygemsLegacyProxyReplicationInitParameters struct {

	// Regular Expression of Asset Paths to pull pre-emptively pull
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// Whether pre-emptive pull is enabled
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled,omitempty" tf:"preemptive_pull_enabled,omitempty"`
}

type RubygemsLegacyProxyReplicationObservation struct {

	// Regular Expression of Asset Paths to pull pre-emptively pull
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// Whether pre-emptive pull is enabled
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled,omitempty" tf:"preemptive_pull_enabled,omitempty"`
}

type RubygemsLegacyProxyReplicationParameters struct {

	// Regular Expression of Asset Paths to pull pre-emptively pull
	// +kubebuilder:validation:Optional
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// Whether pre-emptive pull is enabled
	// +kubebuilder:validation:Optional
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled" tf:"preemptive_pull_enabled,omitempty"`
}

type RubygemsLegacyProxyRepositoryFirewallInitParameters struct {

	// Whether to enable Sonatype Repository Firewall for this Repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether Quarantine functionallity is enabled (if false - just run in Audit mode) - see [documentation](https://help.sonatype.com/en/firewall-quarantine.html).
	Quarantine *bool `json:"quarantine,omitempty" tf:"quarantine,omitempty"`
}

type RubygemsLegacyProxyRepositoryFirewallObservation struct {

	// Internal ID of the Audit & Quarantine Capability created for this Repository
	CapabilityID *string `json:"capabilityId,omitempty" tf:"capability_id,omitempty"`

	// Whether to enable Sonatype Repository Firewall for this Repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether Quarantine functionallity is enabled (if false - just run in Audit mode) - see [documentation](https://help.sonatype.com/en/firewall-quarantine.html).
	Quarantine *bool `json:"quarantine,omitempty" tf:"quarantine,omitempty"`
}

type RubygemsLegacyProxyRepositoryFirewallParameters struct {

	// Whether to enable Sonatype Repository Firewall for this Repository
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// Whether Quarantine functionallity is enabled (if false - just run in Audit mode) - see [documentation](https://help.sonatype.com/en/firewall-quarantine.html).
	// +kubebuilder:validation:Optional
	Quarantine *bool `json:"quarantine,omitempty" tf:"quarantine,omitempty"`
}

type RubygemsLegacyProxyStorageInitParameters struct {

	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type RubygemsLegacyProxyStorageObservation struct {

	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type RubygemsLegacyProxyStorageParameters struct {

	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`
}

// RubygemsLegacyProxySpec defines the desired state of RubygemsLegacyProxy
type RubygemsLegacyProxySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RubygemsLegacyProxyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RubygemsLegacyProxyInitParameters `json:"initProvider,omitempty"`
}

// RubygemsLegacyProxyStatus defines the observed state of RubygemsLegacyProxy.
type RubygemsLegacyProxyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RubygemsLegacyProxyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RubygemsLegacyProxy is the Schema for the RubygemsLegacyProxys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type RubygemsLegacyProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.httpClient) || (has(self.initProvider) && has(self.initProvider.httpClient))",message="spec.forProvider.httpClient is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.negativeCache) || (has(self.initProvider) && has(self.initProvider.negativeCache))",message="spec.forProvider.negativeCache is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.proxy) || (has(self.initProvider) && has(self.initProvider.proxy))",message="spec.forProvider.proxy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   RubygemsLegacyProxySpec   `json:"spec"`
	Status RubygemsLegacyProxyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RubygemsLegacyProxyList contains a list of RubygemsLegacyProxys
type RubygemsLegacyProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RubygemsLegacyProxy `json:"items"`
}

// Repository type metadata.
var (
	RubygemsLegacyProxy_Kind             = "RubygemsLegacyProxy"
	RubygemsLegacyProxy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RubygemsLegacyProxy_Kind}.String()
	RubygemsLegacyProxy_KindAPIVersion   = RubygemsLegacyProxy_Kind + "." + CRDGroupVersion.String()
	RubygemsLegacyProxy_GroupVersionKind = CRDGroupVersion.WithKind(RubygemsLegacyProxy_Kind)
)

func init() {
	SchemeBuilder.Register(&RubygemsLegacyProxy{}, &RubygemsLegacyProxyList{})
}
