// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type TerraformHostedCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type TerraformHostedCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type TerraformHostedCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type TerraformHostedInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *TerraformHostedCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *TerraformHostedStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (attributes) provider specific configuration for this repository (see below for nested schema)
	TerraformSigning *TerraformSigningInitParameters `json:"terraformSigning,omitempty" tf:"terraform_signing,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TerraformHostedObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *TerraformHostedCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *TerraformHostedStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (attributes) provider specific configuration for this repository (see below for nested schema)
	TerraformSigning *TerraformSigningObservation `json:"terraformSigning,omitempty" tf:"terraform_signing,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TerraformHostedParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *TerraformHostedCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *TerraformHostedStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (attributes) provider specific configuration for this repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	TerraformSigning *TerraformSigningParameters `json:"terraformSigning,omitempty" tf:"terraform_signing,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TerraformHostedStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type TerraformHostedStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type TerraformHostedStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	// +kubebuilder:validation:Optional
	WritePolicy *string `json:"writePolicy" tf:"write_policy,omitempty"`
}

type TerraformSigningInitParameters struct {

	// (String) Passphrase for supplied Signing Key (if required)
	// Passphrase for supplied Signing Key (if required)
	Passphrase *string `json:"passphrase,omitempty" tf:"passphrase,omitempty"`

	// -export-secret-key --armor)
	// PGP signing key pair (armored private key e.g. `gpg --export-secret-key --armor`)
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type TerraformSigningObservation struct {

	// (String) Passphrase for supplied Signing Key (if required)
	// Passphrase for supplied Signing Key (if required)
	Passphrase *string `json:"passphrase,omitempty" tf:"passphrase,omitempty"`

	// -export-secret-key --armor)
	// PGP signing key pair (armored private key e.g. `gpg --export-secret-key --armor`)
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`
}

type TerraformSigningParameters struct {

	// (String) Passphrase for supplied Signing Key (if required)
	// Passphrase for supplied Signing Key (if required)
	// +kubebuilder:validation:Optional
	Passphrase *string `json:"passphrase,omitempty" tf:"passphrase,omitempty"`

	// -export-secret-key --armor)
	// PGP signing key pair (armored private key e.g. `gpg --export-secret-key --armor`)
	// +kubebuilder:validation:Optional
	SigningKey *string `json:"signingKey" tf:"signing_key,omitempty"`
}

// TerraformHostedSpec defines the desired state of TerraformHosted
type TerraformHostedSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   TerraformHostedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TerraformHostedInitParameters `json:"initProvider,omitempty"`
}

// TerraformHostedStatus defines the observed state of TerraformHosted.
type TerraformHostedStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               TerraformHostedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TerraformHosted is the Schema for the TerraformHosteds API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type TerraformHosted struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.terraformSigning) || (has(self.initProvider) && has(self.initProvider.terraformSigning))",message="spec.forProvider.terraformSigning is a required parameter"
	Spec   TerraformHostedSpec   `json:"spec"`
	Status TerraformHostedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TerraformHostedList contains a list of TerraformHosteds
type TerraformHostedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TerraformHosted `json:"items"`
}

// Repository type metadata.
var (
	TerraformHosted_Kind             = "TerraformHosted"
	TerraformHosted_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TerraformHosted_Kind}.String()
	TerraformHosted_KindAPIVersion   = TerraformHosted_Kind + "." + CRDGroupVersion.String()
	TerraformHosted_GroupVersionKind = CRDGroupVersion.WithKind(TerraformHosted_Kind)
)

func init() {
	SchemeBuilder.Register(&TerraformHosted{}, &TerraformHostedList{})
}
