apiVersion: capability.nexus.tinyorbit.vn/v1alpha1
kind: Audit
metadata:
  annotations:
    meta.upbound.io/example-id: capability/v1alpha1/audit
  labels:
    testing.upbound.io/example-name: cap_audit
  name: cap-audit
spec:
  forProvider:
    enabled: true
    notes: These are notes from Terraform
