apiVersion: capability.nexus.tinyorbit.vn/v1alpha1
kind: FirewallAuditAndQuarantine
metadata:
  annotations:
    meta.upbound.io/example-id: capability/v1alpha1/firewallauditandquarantine
  labels:
    testing.upbound.io/example-name: firewall_capability
  name: firewall-capability
spec:
  forProvider:
    enabled: true
    notes: Firewall audit and quarantine configuration
    properties:
      quarantine: true
      repository: maven-central
