apiVersion: capability.nexus.tinyorbit.vn/v1alpha1
kind: UISettings
metadata:
  annotations:
    meta.upbound.io/example-id: capability/v1alpha1/uisettings
  labels:
    testing.upbound.io/example-name: ui_settings
  name: ui-settings
spec:
  forProvider:
    enabled: true
    notes: UI settings configuration
    properties:
      title: My Sonatype Nexus Repository
