// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DockerHostedCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type DockerHostedCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type DockerHostedCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type DockerHostedComponentInitParameters struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type DockerHostedComponentObservation struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type DockerHostedComponentParameters struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// +kubebuilder:validation:Optional
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type DockerHostedDockerInitParameters struct {

	// (Boolean) Whether to force authentication (Docker Bearer Token Realm required if false)
	// Whether to force authentication (Docker Bearer Token Realm required if false)
	ForceBasicAuth *bool `json:"forceBasicAuth,omitempty" tf:"force_basic_auth,omitempty"`

	// (Number) Create an HTTP connector at specified port
	// Create an HTTP connector at specified port
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// (Number) Create an HTTPS connector at specified port
	// Create an HTTPS connector at specified port
	HTTPSPort *float64 `json:"httpsPort,omitempty" tf:"https_port,omitempty"`

	// (Boolean) Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	// Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	PathEnabled *bool `json:"pathEnabled,omitempty" tf:"path_enabled,omitempty"`

	// (String) Allows to use subdomain
	// Allows to use subdomain
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// (Boolean) Whether to allow clients to use the V1 API to interact with this repository
	// Whether to allow clients to use the V1 API to interact with this repository
	V1Enabled *bool `json:"v1Enabled,omitempty" tf:"v1_enabled,omitempty"`
}

type DockerHostedDockerObservation struct {

	// (Boolean) Whether to force authentication (Docker Bearer Token Realm required if false)
	// Whether to force authentication (Docker Bearer Token Realm required if false)
	ForceBasicAuth *bool `json:"forceBasicAuth,omitempty" tf:"force_basic_auth,omitempty"`

	// (Number) Create an HTTP connector at specified port
	// Create an HTTP connector at specified port
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// (Number) Create an HTTPS connector at specified port
	// Create an HTTPS connector at specified port
	HTTPSPort *float64 `json:"httpsPort,omitempty" tf:"https_port,omitempty"`

	// (Boolean) Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	// Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	PathEnabled *bool `json:"pathEnabled,omitempty" tf:"path_enabled,omitempty"`

	// (String) Allows to use subdomain
	// Allows to use subdomain
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// (Boolean) Whether to allow clients to use the V1 API to interact with this repository
	// Whether to allow clients to use the V1 API to interact with this repository
	V1Enabled *bool `json:"v1Enabled,omitempty" tf:"v1_enabled,omitempty"`
}

type DockerHostedDockerParameters struct {

	// (Boolean) Whether to force authentication (Docker Bearer Token Realm required if false)
	// Whether to force authentication (Docker Bearer Token Realm required if false)
	// +kubebuilder:validation:Optional
	ForceBasicAuth *bool `json:"forceBasicAuth" tf:"force_basic_auth,omitempty"`

	// (Number) Create an HTTP connector at specified port
	// Create an HTTP connector at specified port
	// +kubebuilder:validation:Optional
	HTTPPort *float64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`

	// (Number) Create an HTTPS connector at specified port
	// Create an HTTPS connector at specified port
	// +kubebuilder:validation:Optional
	HTTPSPort *float64 `json:"httpsPort,omitempty" tf:"https_port,omitempty"`

	// (Boolean) Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	// Allows to use repository name in Docker image paths (only supply for Sonatype Nexus Repository Manager >= 3.83.0)
	// +kubebuilder:validation:Optional
	PathEnabled *bool `json:"pathEnabled,omitempty" tf:"path_enabled,omitempty"`

	// (String) Allows to use subdomain
	// Allows to use subdomain
	// +kubebuilder:validation:Optional
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// (Boolean) Whether to allow clients to use the V1 API to interact with this repository
	// Whether to allow clients to use the V1 API to interact with this repository
	// +kubebuilder:validation:Optional
	V1Enabled *bool `json:"v1Enabled" tf:"v1_enabled,omitempty"`
}

type DockerHostedInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *DockerHostedCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	Component *DockerHostedComponentInitParameters `json:"component,omitempty" tf:"component,omitempty"`

	// (Attributes) Docker specific configuration for this Repository (see below for nested schema)
	Docker *DockerHostedDockerInitParameters `json:"docker,omitempty" tf:"docker,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *DockerHostedStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type DockerHostedObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *DockerHostedCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	Component *DockerHostedComponentObservation `json:"component,omitempty" tf:"component,omitempty"`

	// (Attributes) Docker specific configuration for this Repository (see below for nested schema)
	Docker *DockerHostedDockerObservation `json:"docker,omitempty" tf:"docker,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *DockerHostedStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type DockerHostedParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *DockerHostedCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Component *DockerHostedComponentParameters `json:"component,omitempty" tf:"component,omitempty"`

	// (Attributes) Docker specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Docker *DockerHostedDockerParameters `json:"docker,omitempty" tf:"docker,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *DockerHostedStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type DockerHostedStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	// Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	LatestPolicy *bool `json:"latestPolicy,omitempty" tf:"latest_policy,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type DockerHostedStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	// Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	LatestPolicy *bool `json:"latestPolicy,omitempty" tf:"latest_policy,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type DockerHostedStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	// Whether to allow redeploying the 'latest' tag but defer to the Deployment Policy for all other tags. Only applicable for Hosted Docker/OCI Repositories when Deployment Policy is set to Disable.
	// +kubebuilder:validation:Optional
	LatestPolicy *bool `json:"latestPolicy,omitempty" tf:"latest_policy,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	// +kubebuilder:validation:Optional
	WritePolicy *string `json:"writePolicy" tf:"write_policy,omitempty"`
}

// DockerHostedSpec defines the desired state of DockerHosted
type DockerHostedSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DockerHostedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DockerHostedInitParameters `json:"initProvider,omitempty"`
}

// DockerHostedStatus defines the observed state of DockerHosted.
type DockerHostedStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DockerHostedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DockerHosted is the Schema for the DockerHosteds API. Manage Hosted DOCKER Repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,sonatyperepo}
type DockerHosted struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.docker) || (has(self.initProvider) && has(self.initProvider.docker))",message="spec.forProvider.docker is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   DockerHostedSpec   `json:"spec"`
	Status DockerHostedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DockerHostedList contains a list of DockerHosteds
type DockerHostedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DockerHosted `json:"items"`
}

// Repository type metadata.
var (
	DockerHosted_Kind             = "DockerHosted"
	DockerHosted_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DockerHosted_Kind}.String()
	DockerHosted_KindAPIVersion   = DockerHosted_Kind + "." + CRDGroupVersion.String()
	DockerHosted_GroupVersionKind = CRDGroupVersion.WithKind(DockerHosted_Kind)
)

func init() {
	SchemeBuilder.Register(&DockerHosted{}, &DockerHostedList{})
}
