// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type GitlfsHostedCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type GitlfsHostedCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type GitlfsHostedCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type GitlfsHostedComponentInitParameters struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type GitlfsHostedComponentObservation struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type GitlfsHostedComponentParameters struct {

	// (Boolean) Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Repository Firewall)
	// +kubebuilder:validation:Optional
	ProprietaryComponents *bool `json:"proprietaryComponents,omitempty" tf:"proprietary_components,omitempty"`
}

type GitlfsHostedInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *GitlfsHostedCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	Component *GitlfsHostedComponentInitParameters `json:"component,omitempty" tf:"component,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *GitlfsHostedStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitlfsHostedObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *GitlfsHostedCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	Component *GitlfsHostedComponentObservation `json:"component,omitempty" tf:"component,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *GitlfsHostedStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitlfsHostedParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *GitlfsHostedCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Component configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Component *GitlfsHostedComponentParameters `json:"component,omitempty" tf:"component,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *GitlfsHostedStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type GitlfsHostedStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type GitlfsHostedStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	WritePolicy *string `json:"writePolicy,omitempty" tf:"write_policy,omitempty"`
}

type GitlfsHostedStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`

	// (String) Controls if deployments of and updates to assets are allowed
	// Controls if deployments of and updates to assets are allowed
	// +kubebuilder:validation:Optional
	WritePolicy *string `json:"writePolicy" tf:"write_policy,omitempty"`
}

// GitlfsHostedSpec defines the desired state of GitlfsHosted
type GitlfsHostedSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GitlfsHostedParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GitlfsHostedInitParameters `json:"initProvider,omitempty"`
}

// GitlfsHostedStatus defines the observed state of GitlfsHosted.
type GitlfsHostedStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GitlfsHostedObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GitlfsHosted is the Schema for the GitlfsHosteds API. Manage Hosted GITLFS Repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,sonatyperepo}
type GitlfsHosted struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   GitlfsHostedSpec   `json:"spec"`
	Status GitlfsHostedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GitlfsHostedList contains a list of GitlfsHosteds
type GitlfsHostedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GitlfsHosted `json:"items"`
}

// Repository type metadata.
var (
	GitlfsHosted_Kind             = "GitlfsHosted"
	GitlfsHosted_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GitlfsHosted_Kind}.String()
	GitlfsHosted_KindAPIVersion   = GitlfsHosted_Kind + "." + CRDGroupVersion.String()
	GitlfsHosted_GroupVersionKind = CRDGroupVersion.WithKind(GitlfsHosted_Kind)
)

func init() {
	SchemeBuilder.Register(&GitlfsHosted{}, &GitlfsHostedList{})
}
