// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RawGroupCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RawGroupCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RawGroupCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type RawGroupGroupInitParameters struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`
}

type RawGroupGroupObservation struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`
}

type RawGroupGroupParameters struct {

	// (List of String) Member repositories' names
	// Member repositories' names
	// +kubebuilder:validation:Optional
	MemberNames []*string `json:"memberNames,omitempty" tf:"member_names,omitempty"`
}

type RawGroupInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *RawGroupCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	Group *RawGroupGroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Raw specific configuration for this Repository (see below for nested schema)
	Raw *RawInitParameters `json:"raw,omitempty" tf:"raw,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *RawGroupStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RawGroupObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *RawGroupCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	Group *RawGroupGroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Raw specific configuration for this Repository (see below for nested schema)
	Raw *RawObservation `json:"raw,omitempty" tf:"raw,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *RawGroupStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RawGroupParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *RawGroupCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) Group specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Group *RawGroupGroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Raw specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Raw *RawParameters `json:"raw,omitempty" tf:"raw,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *RawGroupStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RawGroupStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type RawGroupStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type RawGroupStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`
}

type RawInitParameters struct {

	// (String) Content Disposition
	// Content Disposition
	ContentDisposition *string `json:"contentDisposition,omitempty" tf:"content_disposition,omitempty"`
}

type RawObservation struct {

	// (String) Content Disposition
	// Content Disposition
	ContentDisposition *string `json:"contentDisposition,omitempty" tf:"content_disposition,omitempty"`
}

type RawParameters struct {

	// (String) Content Disposition
	// Content Disposition
	// +kubebuilder:validation:Optional
	ContentDisposition *string `json:"contentDisposition" tf:"content_disposition,omitempty"`
}

// RawGroupSpec defines the desired state of RawGroup
type RawGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RawGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RawGroupInitParameters `json:"initProvider,omitempty"`
}

// RawGroupStatus defines the observed state of RawGroup.
type RawGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RawGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RawGroup is the Schema for the RawGroups API. Manage Group RAW Repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,sonatyperepo}
type RawGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.group) || (has(self.initProvider) && has(self.initProvider.group))",message="spec.forProvider.group is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.raw) || (has(self.initProvider) && has(self.initProvider.raw))",message="spec.forProvider.raw is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	Spec   RawGroupSpec   `json:"spec"`
	Status RawGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RawGroupList contains a list of RawGroups
type RawGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RawGroup `json:"items"`
}

// Repository type metadata.
var (
	RawGroup_Kind             = "RawGroup"
	RawGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RawGroup_Kind}.String()
	RawGroup_KindAPIVersion   = RawGroup_Kind + "." + CRDGroupVersion.String()
	RawGroup_GroupVersionKind = CRDGroupVersion.WithKind(RawGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&RawGroup{}, &RawGroupList{})
}
