// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SwiftInitParameters struct {

	// (Boolean) Indicates if this repository requires authentication overriding anonymous access.
	// Indicates if this repository requires authentication overriding anonymous access.
	RequireAuthentication *bool `json:"requireAuthentication,omitempty" tf:"require_authentication,omitempty"`
}

type SwiftObservation struct {

	// (Boolean) Indicates if this repository requires authentication overriding anonymous access.
	// Indicates if this repository requires authentication overriding anonymous access.
	RequireAuthentication *bool `json:"requireAuthentication,omitempty" tf:"require_authentication,omitempty"`
}

type SwiftParameters struct {

	// (Boolean) Indicates if this repository requires authentication overriding anonymous access.
	// Indicates if this repository requires authentication overriding anonymous access.
	// +kubebuilder:validation:Optional
	RequireAuthentication *bool `json:"requireAuthentication,omitempty" tf:"require_authentication,omitempty"`
}

type SwiftProxyCleanupInitParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type SwiftProxyCleanupObservation struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type SwiftProxyCleanupParameters struct {

	// (Set of String) Set of Cleanup Policies that will apply to this Repository
	// Set of Cleanup Policies that will apply to this Repository
	// +kubebuilder:validation:Optional
	// +listType=set
	PolicyNames []*string `json:"policyNames,omitempty" tf:"policy_names,omitempty"`
}

type SwiftProxyHTTPClientAuthenticationInitParameters struct {

	// (String, Sensitive) Bearer Token used when Authentication Type == bearerToken
	// Bearer Token used when Authentication Type == bearerToken
	BearerTokenSecretRef *v2.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// (String) NTLM Domain
	// NTLM Domain
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// (String) NTLM Host
	// NTLM Host
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// (String, Sensitive) Password
	// Password
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// emptive authentication. Use with caution. Defaults to false.
	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// (String) Authentication type
	// Authentication type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Username
	// Username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SwiftProxyHTTPClientAuthenticationObservation struct {

	// (String) NTLM Domain
	// NTLM Domain
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// (String) NTLM Host
	// NTLM Host
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// emptive authentication. Use with caution. Defaults to false.
	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// (String) Authentication type
	// Authentication type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Username
	// Username
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SwiftProxyHTTPClientAuthenticationParameters struct {

	// (String, Sensitive) Bearer Token used when Authentication Type == bearerToken
	// Bearer Token used when Authentication Type == bearerToken
	// +kubebuilder:validation:Optional
	BearerTokenSecretRef *v2.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// (String) NTLM Domain
	// NTLM Domain
	// +kubebuilder:validation:Optional
	NtlmDomain *string `json:"ntlmDomain,omitempty" tf:"ntlm_domain,omitempty"`

	// (String) NTLM Host
	// NTLM Host
	// +kubebuilder:validation:Optional
	NtlmHost *string `json:"ntlmHost,omitempty" tf:"ntlm_host,omitempty"`

	// (String, Sensitive) Password
	// Password
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// emptive authentication. Use with caution. Defaults to false.
	// Whether to use pre-emptive authentication. Use with caution. Defaults to false.
	// +kubebuilder:validation:Optional
	Preemptive *bool `json:"preemptive,omitempty" tf:"preemptive,omitempty"`

	// (String) Authentication type
	// Authentication type
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Username
	// Username
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SwiftProxyHTTPClientConnectionInitParameters struct {

	// (Boolean) Whether to enable redirects to the same location (may be required by some servers)
	// Whether to enable redirects to the same location (may be required by some servers)
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// (Boolean) Whether to allow cookies to be stored and used
	// Whether to allow cookies to be stored and used
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// (Number) Total retries if the initial connection attempt suffers a timeout
	// Total retries if the initial connection attempt suffers a timeout
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// (Number) Seconds to wait for activity before stopping and retrying the connection
	// Seconds to wait for activity before stopping and retrying the connection
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Agent header in HTTP requests
	// Custom fragment to append to User-Agent header in HTTP requests
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type SwiftProxyHTTPClientConnectionObservation struct {

	// (Boolean) Whether to enable redirects to the same location (may be required by some servers)
	// Whether to enable redirects to the same location (may be required by some servers)
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// (Boolean) Whether to allow cookies to be stored and used
	// Whether to allow cookies to be stored and used
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// (Number) Total retries if the initial connection attempt suffers a timeout
	// Total retries if the initial connection attempt suffers a timeout
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// (Number) Seconds to wait for activity before stopping and retrying the connection
	// Seconds to wait for activity before stopping and retrying the connection
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Agent header in HTTP requests
	// Custom fragment to append to User-Agent header in HTTP requests
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type SwiftProxyHTTPClientConnectionParameters struct {

	// (Boolean) Whether to enable redirects to the same location (may be required by some servers)
	// Whether to enable redirects to the same location (may be required by some servers)
	// +kubebuilder:validation:Optional
	EnableCircularRedirects *bool `json:"enableCircularRedirects,omitempty" tf:"enable_circular_redirects,omitempty"`

	// (Boolean) Whether to allow cookies to be stored and used
	// Whether to allow cookies to be stored and used
	// +kubebuilder:validation:Optional
	EnableCookies *bool `json:"enableCookies,omitempty" tf:"enable_cookies,omitempty"`

	// (Number) Total retries if the initial connection attempt suffers a timeout
	// Total retries if the initial connection attempt suffers a timeout
	// +kubebuilder:validation:Optional
	Retries *float64 `json:"retries,omitempty" tf:"retries,omitempty"`

	// (Number) Seconds to wait for activity before stopping and retrying the connection
	// Seconds to wait for activity before stopping and retrying the connection
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// (Boolean) Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	// Use certificates stored in the Nexus Repository Manager truststore to connect to external systems
	// +kubebuilder:validation:Optional
	UseTrustStore *bool `json:"useTrustStore,omitempty" tf:"use_trust_store,omitempty"`

	// Agent header in HTTP requests
	// Custom fragment to append to User-Agent header in HTTP requests
	// +kubebuilder:validation:Optional
	UserAgentSuffix *string `json:"userAgentSuffix,omitempty" tf:"user_agent_suffix,omitempty"`
}

type SwiftProxyHTTPClientInitParameters struct {

	// (Attributes) Authentication to upstream Repository (see below for nested schema)
	Authentication *SwiftProxyHTTPClientAuthenticationInitParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// block outbound connections if remote peer is detected as unreachable/unresponsive
	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	AutoBlock *bool `json:"autoBlock,omitempty" tf:"auto_block,omitempty"`

	// (Boolean) Whether to block outbound connections on the repository
	// Whether to block outbound connections on the repository
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// (Attributes) HTTP Client Connection configuration for this Repository (see below for nested schema)
	Connection *SwiftProxyHTTPClientConnectionInitParameters `json:"connection,omitempty" tf:"connection,omitempty"`
}

type SwiftProxyHTTPClientObservation struct {

	// (Attributes) Authentication to upstream Repository (see below for nested schema)
	Authentication *SwiftProxyHTTPClientAuthenticationObservation `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// block outbound connections if remote peer is detected as unreachable/unresponsive
	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	AutoBlock *bool `json:"autoBlock,omitempty" tf:"auto_block,omitempty"`

	// (Boolean) Whether to block outbound connections on the repository
	// Whether to block outbound connections on the repository
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// (Attributes) HTTP Client Connection configuration for this Repository (see below for nested schema)
	Connection *SwiftProxyHTTPClientConnectionObservation `json:"connection,omitempty" tf:"connection,omitempty"`
}

type SwiftProxyHTTPClientParameters struct {

	// (Attributes) Authentication to upstream Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Authentication *SwiftProxyHTTPClientAuthenticationParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// block outbound connections if remote peer is detected as unreachable/unresponsive
	// Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
	// +kubebuilder:validation:Optional
	AutoBlock *bool `json:"autoBlock" tf:"auto_block,omitempty"`

	// (Boolean) Whether to block outbound connections on the repository
	// Whether to block outbound connections on the repository
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked" tf:"blocked,omitempty"`

	// (Attributes) HTTP Client Connection configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Connection *SwiftProxyHTTPClientConnectionParameters `json:"connection,omitempty" tf:"connection,omitempty"`
}

type SwiftProxyInitParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *SwiftProxyCleanupInitParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) HTTP Client configuration for this Repository (see below for nested schema)
	HTTPClient *SwiftProxyHTTPClientInitParameters `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	// (Attributes) Negative Cache configuration for this Repository (see below for nested schema)
	NegativeCache *SwiftProxyNegativeCacheInitParameters `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Proxy specific configuration for this Repository (see below for nested schema)
	Proxy *SwiftProxyProxyInitParameters `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// (Attributes) Replication configuration for this Repository (see below for nested schema)
	Replication *SwiftProxyReplicationInitParameters `json:"replication,omitempty" tf:"replication,omitempty"`

	// (String) Routing Rule
	// Routing Rule
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *SwiftProxyStorageInitParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (Attributes) Swift specific configuration for this Repository (see below for nested schema)
	Swift *SwiftInitParameters `json:"swift,omitempty" tf:"swift,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type SwiftProxyNegativeCacheInitParameters struct {

	// (Boolean) Whether to cache responses for content not present in the proxied repository
	// Whether to cache responses for content not present in the proxied repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) How long to cache the fact that a file was not found in the repository (in minutes)
	// How long to cache the fact that a file was not found in the repository (in minutes)
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type SwiftProxyNegativeCacheObservation struct {

	// (Boolean) Whether to cache responses for content not present in the proxied repository
	// Whether to cache responses for content not present in the proxied repository
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) How long to cache the fact that a file was not found in the repository (in minutes)
	// How long to cache the fact that a file was not found in the repository (in minutes)
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type SwiftProxyNegativeCacheParameters struct {

	// (Boolean) Whether to cache responses for content not present in the proxied repository
	// Whether to cache responses for content not present in the proxied repository
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Number) How long to cache the fact that a file was not found in the repository (in minutes)
	// How long to cache the fact that a file was not found in the repository (in minutes)
	// +kubebuilder:validation:Optional
	TimeToLive *float64 `json:"timeToLive,omitempty" tf:"time_to_live,omitempty"`
}

type SwiftProxyObservation struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	Cleanup *SwiftProxyCleanupObservation `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) HTTP Client configuration for this Repository (see below for nested schema)
	HTTPClient *SwiftProxyHTTPClientObservation `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Attributes) Negative Cache configuration for this Repository (see below for nested schema)
	NegativeCache *SwiftProxyNegativeCacheObservation `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Proxy specific configuration for this Repository (see below for nested schema)
	Proxy *SwiftProxyProxyObservation `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// (Attributes) Replication configuration for this Repository (see below for nested schema)
	Replication *SwiftProxyReplicationObservation `json:"replication,omitempty" tf:"replication,omitempty"`

	// (String) Routing Rule
	// Routing Rule
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	Storage *SwiftProxyStorageObservation `json:"storage,omitempty" tf:"storage,omitempty"`

	// (Attributes) Swift specific configuration for this Repository (see below for nested schema)
	Swift *SwiftObservation `json:"swift,omitempty" tf:"swift,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type SwiftProxyParameters struct {

	// (Attributes) Repository Cleanup configuration (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cleanup *SwiftProxyCleanupParameters `json:"cleanup,omitempty" tf:"cleanup,omitempty"`

	// (Attributes) HTTP Client configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	HTTPClient *SwiftProxyHTTPClientParameters `json:"httpClient,omitempty" tf:"http_client,omitempty"`

	// (Attributes) Negative Cache configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	NegativeCache *SwiftProxyNegativeCacheParameters `json:"negativeCache,omitempty" tf:"negative_cache,omitempty"`

	// (Boolean) Whether this Repository is online and accepting incoming requests
	// Whether this Repository is online and accepting incoming requests
	// +kubebuilder:validation:Optional
	Online *bool `json:"online,omitempty" tf:"online,omitempty"`

	// (Attributes) Proxy specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Proxy *SwiftProxyProxyParameters `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// (Attributes) Replication configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Replication *SwiftProxyReplicationParameters `json:"replication,omitempty" tf:"replication,omitempty"`

	// (String) Routing Rule
	// Routing Rule
	// +kubebuilder:validation:Optional
	RoutingRule *string `json:"routingRule,omitempty" tf:"routing_rule,omitempty"`

	// (Attributes) Storage configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Storage *SwiftProxyStorageParameters `json:"storage,omitempty" tf:"storage,omitempty"`

	// (Attributes) Swift specific configuration for this Repository (see below for nested schema)
	// +kubebuilder:validation:Optional
	Swift *SwiftParameters `json:"swift,omitempty" tf:"swift,omitempty"`

	// (String) URL to access the Repository
	// URL to access the Repository
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type SwiftProxyProxyInitParameters struct {

	// (Number) How long to cache artifacts before rechecking the remote repository (in minutes)
	// How long to cache artifacts before rechecking the remote repository (in minutes)
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// (Number) How long to cache metadata before rechecking the remote repository (in minutes)
	// How long to cache metadata before rechecking the remote repository (in minutes)
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// (String) Location of the remote repository being proxied
	// Location of the remote repository being proxied
	RemoteURL *string `json:"remoteUrl,omitempty" tf:"remote_url,omitempty"`
}

type SwiftProxyProxyObservation struct {

	// (Number) How long to cache artifacts before rechecking the remote repository (in minutes)
	// How long to cache artifacts before rechecking the remote repository (in minutes)
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// (Number) How long to cache metadata before rechecking the remote repository (in minutes)
	// How long to cache metadata before rechecking the remote repository (in minutes)
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// (String) Location of the remote repository being proxied
	// Location of the remote repository being proxied
	RemoteURL *string `json:"remoteUrl,omitempty" tf:"remote_url,omitempty"`
}

type SwiftProxyProxyParameters struct {

	// (Number) How long to cache artifacts before rechecking the remote repository (in minutes)
	// How long to cache artifacts before rechecking the remote repository (in minutes)
	// +kubebuilder:validation:Optional
	ContentMaxAge *float64 `json:"contentMaxAge,omitempty" tf:"content_max_age,omitempty"`

	// (Number) How long to cache metadata before rechecking the remote repository (in minutes)
	// How long to cache metadata before rechecking the remote repository (in minutes)
	// +kubebuilder:validation:Optional
	MetadataMaxAge *float64 `json:"metadataMaxAge,omitempty" tf:"metadata_max_age,omitempty"`

	// (String) Location of the remote repository being proxied
	// Location of the remote repository being proxied
	// +kubebuilder:validation:Optional
	RemoteURL *string `json:"remoteUrl" tf:"remote_url,omitempty"`
}

type SwiftProxyReplicationInitParameters struct {

	// emptively pull
	// Regular Expression of Asset Paths to pull pre-emptively pull
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// emptive pull is enabled
	// Whether pre-emptive pull is enabled
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled,omitempty" tf:"preemptive_pull_enabled,omitempty"`
}

type SwiftProxyReplicationObservation struct {

	// emptively pull
	// Regular Expression of Asset Paths to pull pre-emptively pull
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// emptive pull is enabled
	// Whether pre-emptive pull is enabled
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled,omitempty" tf:"preemptive_pull_enabled,omitempty"`
}

type SwiftProxyReplicationParameters struct {

	// emptively pull
	// Regular Expression of Asset Paths to pull pre-emptively pull
	// +kubebuilder:validation:Optional
	AssetPathRegex *string `json:"assetPathRegex,omitempty" tf:"asset_path_regex,omitempty"`

	// emptive pull is enabled
	// Whether pre-emptive pull is enabled
	// +kubebuilder:validation:Optional
	PreemptivePullEnabled *bool `json:"preemptivePullEnabled" tf:"preemptive_pull_enabled,omitempty"`
}

type SwiftProxyStorageInitParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type SwiftProxyStorageObservation struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	BlobStoreName *string `json:"blobStoreName,omitempty" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation,omitempty" tf:"strict_content_type_validation,omitempty"`
}

type SwiftProxyStorageParameters struct {

	// (String) Name of the Blob Store to use
	// Name of the Blob Store to use
	// +kubebuilder:validation:Optional
	BlobStoreName *string `json:"blobStoreName" tf:"blob_store_name,omitempty"`

	// (Boolean) Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// Whether this Repository validates that all content uploaded to this repository is of a MIME type appropriate for the repository format
	// +kubebuilder:validation:Optional
	StrictContentTypeValidation *bool `json:"strictContentTypeValidation" tf:"strict_content_type_validation,omitempty"`
}

// SwiftProxySpec defines the desired state of SwiftProxy
type SwiftProxySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SwiftProxyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SwiftProxyInitParameters `json:"initProvider,omitempty"`
}

// SwiftProxyStatus defines the observed state of SwiftProxy.
type SwiftProxyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SwiftProxyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SwiftProxy is the Schema for the SwiftProxys API. Manage Proxy SWIFT Repositories.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,sonatyperepo}
type SwiftProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.httpClient) || (has(self.initProvider) && has(self.initProvider.httpClient))",message="spec.forProvider.httpClient is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.negativeCache) || (has(self.initProvider) && has(self.initProvider.negativeCache))",message="spec.forProvider.negativeCache is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.online) || (has(self.initProvider) && has(self.initProvider.online))",message="spec.forProvider.online is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.proxy) || (has(self.initProvider) && has(self.initProvider.proxy))",message="spec.forProvider.proxy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.storage) || (has(self.initProvider) && has(self.initProvider.storage))",message="spec.forProvider.storage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.swift) || (has(self.initProvider) && has(self.initProvider.swift))",message="spec.forProvider.swift is a required parameter"
	Spec   SwiftProxySpec   `json:"spec"`
	Status SwiftProxyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SwiftProxyList contains a list of SwiftProxys
type SwiftProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SwiftProxy `json:"items"`
}

// Repository type metadata.
var (
	SwiftProxy_Kind             = "SwiftProxy"
	SwiftProxy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SwiftProxy_Kind}.String()
	SwiftProxy_KindAPIVersion   = SwiftProxy_Kind + "." + CRDGroupVersion.String()
	SwiftProxy_GroupVersionKind = CRDGroupVersion.WithKind(SwiftProxy_Kind)
)

func init() {
	SchemeBuilder.Register(&SwiftProxy{}, &SwiftProxyList{})
}
