// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/tinyorbitvn/provider-nexus/apis/namespaced/blobstore/v1alpha1"
	v1alpha1capability "github.com/tinyorbitvn/provider-nexus/apis/namespaced/capability/v1alpha1"
	v1alpha1cleanup "github.com/tinyorbitvn/provider-nexus/apis/namespaced/cleanup/v1alpha1"
	v1alpha1content "github.com/tinyorbitvn/provider-nexus/apis/namespaced/content/v1alpha1"
	v1alpha1privilege "github.com/tinyorbitvn/provider-nexus/apis/namespaced/privilege/v1alpha1"
	v1alpha1repository "github.com/tinyorbitvn/provider-nexus/apis/namespaced/repository/v1alpha1"
	v1alpha1routing "github.com/tinyorbitvn/provider-nexus/apis/namespaced/routing/v1alpha1"
	v1alpha1security "github.com/tinyorbitvn/provider-nexus/apis/namespaced/security/v1alpha1"
	v1alpha1system "github.com/tinyorbitvn/provider-nexus/apis/namespaced/system/v1alpha1"
	v1alpha1task "github.com/tinyorbitvn/provider-nexus/apis/namespaced/task/v1alpha1"
	v1alpha1namespaced "github.com/tinyorbitvn/provider-nexus/apis/namespaced/v1alpha1"
	v1beta1 "github.com/tinyorbitvn/provider-nexus/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1capability.SchemeBuilder.AddToScheme,
		v1alpha1cleanup.SchemeBuilder.AddToScheme,
		v1alpha1content.SchemeBuilder.AddToScheme,
		v1alpha1privilege.SchemeBuilder.AddToScheme,
		v1alpha1repository.SchemeBuilder.AddToScheme,
		v1alpha1routing.SchemeBuilder.AddToScheme,
		v1alpha1security.SchemeBuilder.AddToScheme,
		v1alpha1system.SchemeBuilder.AddToScheme,
		v1alpha1task.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
