// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AnonymousAccessInitParameters struct {

	// (Boolean) Whether or not Anonymous Access is enabled
	// Whether or not Anonymous Access is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The name of the authentication realm for the anonymous account
	// The name of the authentication realm for the anonymous account
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) The username of the anonymous account
	// The username of the anonymous account
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type AnonymousAccessObservation struct {

	// (Boolean) Whether or not Anonymous Access is enabled
	// Whether or not Anonymous Access is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String) The name of the authentication realm for the anonymous account
	// The name of the authentication realm for the anonymous account
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) The username of the anonymous account
	// The username of the anonymous account
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type AnonymousAccessParameters struct {

	// (Boolean) Whether or not Anonymous Access is enabled
	// Whether or not Anonymous Access is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The name of the authentication realm for the anonymous account
	// The name of the authentication realm for the anonymous account
	// +kubebuilder:validation:Optional
	RealmName *string `json:"realmName,omitempty" tf:"realm_name,omitempty"`

	// (String) The username of the anonymous account
	// The username of the anonymous account
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// AnonymousAccessSpec defines the desired state of AnonymousAccess
type AnonymousAccessSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   AnonymousAccessParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AnonymousAccessInitParameters `json:"initProvider,omitempty"`
}

// AnonymousAccessStatus defines the observed state of AnonymousAccess.
type AnonymousAccessStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               AnonymousAccessObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AnonymousAccess is the Schema for the AnonymousAccesss API. Manage Anonymous Access
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type AnonymousAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmName) || (has(self.initProvider) && has(self.initProvider.realmName))",message="spec.forProvider.realmName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userId) || (has(self.initProvider) && has(self.initProvider.userId))",message="spec.forProvider.userId is a required parameter"
	Spec   AnonymousAccessSpec   `json:"spec"`
	Status AnonymousAccessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AnonymousAccessList contains a list of AnonymousAccesss
type AnonymousAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnonymousAccess `json:"items"`
}

// Repository type metadata.
var (
	AnonymousAccess_Kind             = "AnonymousAccess"
	AnonymousAccess_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AnonymousAccess_Kind}.String()
	AnonymousAccess_KindAPIVersion   = AnonymousAccess_Kind + "." + CRDGroupVersion.String()
	AnonymousAccess_GroupVersionKind = CRDGroupVersion.WithKind(AnonymousAccess_Kind)
)

func init() {
	SchemeBuilder.Register(&AnonymousAccess{}, &AnonymousAccessList{})
}
