// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConfigMailInitParameters struct {

	// (Boolean) Whether Email Server is enabled
	// Whether Email Server is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) From Address to use when sending emails
	// From Address to use when sending emails
	FromAddress *string `json:"fromAddress,omitempty" tf:"from_address,omitempty"`

	// (String) SMTP Server Hostname
	// SMTP Server Hostname
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Boolean) Use certificate connected to the Nexus Repository Truststore
	// Use certificate connected to the Nexus Repository Truststore
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// (String, Sensitive) Password to use for authentication with SMTP Server
	// Password to use for authentication with SMTP Server
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (Number) SMTP Server Port
	// SMTP Server Port
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Enable SSL/TLS encryption upon connection
	// Enable SSL/TLS encryption upon connection
	SSLOnConnectEnabled *bool `json:"sslOnConnectEnabled,omitempty" tf:"ssl_on_connect_enabled,omitempty"`

	// (Boolean) Enable server identity check
	// Enable server identity check
	SSLServerIdentityCheckEnabled *bool `json:"sslServerIdentityCheckEnabled,omitempty" tf:"ssl_server_identity_check_enabled,omitempty"`

	// (Boolean) Enable STARTTLS support for insecure connections
	// Enable STARTTLS support for insecure connections
	StartTLSEnabled *bool `json:"startTlsEnabled,omitempty" tf:"start_tls_enabled,omitempty"`

	// (Boolean) Require STARTTLS support
	// Require STARTTLS support
	StartTLSRequired *bool `json:"startTlsRequired,omitempty" tf:"start_tls_required,omitempty"`

	// (String) A prefix to use in Subject Lines for emails that are sent
	// A prefix to use in Subject Lines for emails that are sent
	SubjectPrefix *string `json:"subjectPrefix,omitempty" tf:"subject_prefix,omitempty"`

	// (String) Username to use for authentication with SMTP Server
	// Username to use for authentication with SMTP Server
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConfigMailObservation struct {

	// (Boolean) Whether Email Server is enabled
	// Whether Email Server is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) From Address to use when sending emails
	// From Address to use when sending emails
	FromAddress *string `json:"fromAddress,omitempty" tf:"from_address,omitempty"`

	// (String) SMTP Server Hostname
	// SMTP Server Hostname
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Use certificate connected to the Nexus Repository Truststore
	// Use certificate connected to the Nexus Repository Truststore
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// (Number) SMTP Server Port
	// SMTP Server Port
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Enable SSL/TLS encryption upon connection
	// Enable SSL/TLS encryption upon connection
	SSLOnConnectEnabled *bool `json:"sslOnConnectEnabled,omitempty" tf:"ssl_on_connect_enabled,omitempty"`

	// (Boolean) Enable server identity check
	// Enable server identity check
	SSLServerIdentityCheckEnabled *bool `json:"sslServerIdentityCheckEnabled,omitempty" tf:"ssl_server_identity_check_enabled,omitempty"`

	// (Boolean) Enable STARTTLS support for insecure connections
	// Enable STARTTLS support for insecure connections
	StartTLSEnabled *bool `json:"startTlsEnabled,omitempty" tf:"start_tls_enabled,omitempty"`

	// (Boolean) Require STARTTLS support
	// Require STARTTLS support
	StartTLSRequired *bool `json:"startTlsRequired,omitempty" tf:"start_tls_required,omitempty"`

	// (String) A prefix to use in Subject Lines for emails that are sent
	// A prefix to use in Subject Lines for emails that are sent
	SubjectPrefix *string `json:"subjectPrefix,omitempty" tf:"subject_prefix,omitempty"`

	// (String) Username to use for authentication with SMTP Server
	// Username to use for authentication with SMTP Server
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConfigMailParameters struct {

	// (Boolean) Whether Email Server is enabled
	// Whether Email Server is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) From Address to use when sending emails
	// From Address to use when sending emails
	// +kubebuilder:validation:Optional
	FromAddress *string `json:"fromAddress,omitempty" tf:"from_address,omitempty"`

	// (String) SMTP Server Hostname
	// SMTP Server Hostname
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (Boolean) Use certificate connected to the Nexus Repository Truststore
	// Use certificate connected to the Nexus Repository Truststore
	// +kubebuilder:validation:Optional
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// (String, Sensitive) Password to use for authentication with SMTP Server
	// Password to use for authentication with SMTP Server
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (Number) SMTP Server Port
	// SMTP Server Port
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Enable SSL/TLS encryption upon connection
	// Enable SSL/TLS encryption upon connection
	// +kubebuilder:validation:Optional
	SSLOnConnectEnabled *bool `json:"sslOnConnectEnabled,omitempty" tf:"ssl_on_connect_enabled,omitempty"`

	// (Boolean) Enable server identity check
	// Enable server identity check
	// +kubebuilder:validation:Optional
	SSLServerIdentityCheckEnabled *bool `json:"sslServerIdentityCheckEnabled,omitempty" tf:"ssl_server_identity_check_enabled,omitempty"`

	// (Boolean) Enable STARTTLS support for insecure connections
	// Enable STARTTLS support for insecure connections
	// +kubebuilder:validation:Optional
	StartTLSEnabled *bool `json:"startTlsEnabled,omitempty" tf:"start_tls_enabled,omitempty"`

	// (Boolean) Require STARTTLS support
	// Require STARTTLS support
	// +kubebuilder:validation:Optional
	StartTLSRequired *bool `json:"startTlsRequired,omitempty" tf:"start_tls_required,omitempty"`

	// (String) A prefix to use in Subject Lines for emails that are sent
	// A prefix to use in Subject Lines for emails that are sent
	// +kubebuilder:validation:Optional
	SubjectPrefix *string `json:"subjectPrefix,omitempty" tf:"subject_prefix,omitempty"`

	// (String) Username to use for authentication with SMTP Server
	// Username to use for authentication with SMTP Server
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ConfigMailSpec defines the desired state of ConfigMail
type ConfigMailSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ConfigMailParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigMailInitParameters `json:"initProvider,omitempty"`
}

// ConfigMailStatus defines the observed state of ConfigMail.
type ConfigMailStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConfigMailObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConfigMail is the Schema for the ConfigMails API. Configure the System Email Server
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type ConfigMail struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fromAddress) || (has(self.initProvider) && has(self.initProvider.fromAddress))",message="spec.forProvider.fromAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.host) || (has(self.initProvider) && has(self.initProvider.host))",message="spec.forProvider.host is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nexusTrustStoreEnabled) || (has(self.initProvider) && has(self.initProvider.nexusTrustStoreEnabled))",message="spec.forProvider.nexusTrustStoreEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.port) || (has(self.initProvider) && has(self.initProvider.port))",message="spec.forProvider.port is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sslOnConnectEnabled) || (has(self.initProvider) && has(self.initProvider.sslOnConnectEnabled))",message="spec.forProvider.sslOnConnectEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sslServerIdentityCheckEnabled) || (has(self.initProvider) && has(self.initProvider.sslServerIdentityCheckEnabled))",message="spec.forProvider.sslServerIdentityCheckEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startTlsEnabled) || (has(self.initProvider) && has(self.initProvider.startTlsEnabled))",message="spec.forProvider.startTlsEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startTlsRequired) || (has(self.initProvider) && has(self.initProvider.startTlsRequired))",message="spec.forProvider.startTlsRequired is a required parameter"
	Spec   ConfigMailSpec   `json:"spec"`
	Status ConfigMailStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigMailList contains a list of ConfigMails
type ConfigMailList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigMail `json:"items"`
}

// Repository type metadata.
var (
	ConfigMail_Kind             = "ConfigMail"
	ConfigMail_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConfigMail_Kind}.String()
	ConfigMail_KindAPIVersion   = ConfigMail_Kind + "." + CRDGroupVersion.String()
	ConfigMail_GroupVersionKind = CRDGroupVersion.WithKind(ConfigMail_Kind)
)

func init() {
	SchemeBuilder.Register(&ConfigMail{}, &ConfigMailList{})
}
