//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccess) DeepCopyInto(out *AnonymousAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccess.
func (in *AnonymousAccess) DeepCopy() *AnonymousAccess {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymousAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessInitParameters) DeepCopyInto(out *AnonymousAccessInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessInitParameters.
func (in *AnonymousAccessInitParameters) DeepCopy() *AnonymousAccessInitParameters {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessList) DeepCopyInto(out *AnonymousAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnonymousAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessList.
func (in *AnonymousAccessList) DeepCopy() *AnonymousAccessList {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnonymousAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessObservation) DeepCopyInto(out *AnonymousAccessObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessObservation.
func (in *AnonymousAccessObservation) DeepCopy() *AnonymousAccessObservation {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessParameters) DeepCopyInto(out *AnonymousAccessParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RealmName != nil {
		in, out := &in.RealmName, &out.RealmName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessParameters.
func (in *AnonymousAccessParameters) DeepCopy() *AnonymousAccessParameters {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessSpec) DeepCopyInto(out *AnonymousAccessSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessSpec.
func (in *AnonymousAccessSpec) DeepCopy() *AnonymousAccessSpec {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnonymousAccessStatus) DeepCopyInto(out *AnonymousAccessStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnonymousAccessStatus.
func (in *AnonymousAccessStatus) DeepCopy() *AnonymousAccessStatus {
	if in == nil {
		return nil
	}
	out := new(AnonymousAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationInitParameters) DeepCopyInto(out *AuthenticationInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationInitParameters.
func (in *AuthenticationInitParameters) DeepCopy() *AuthenticationInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthenticationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationObservation) DeepCopyInto(out *AuthenticationObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationObservation.
func (in *AuthenticationObservation) DeepCopy() *AuthenticationObservation {
	if in == nil {
		return nil
	}
	out := new(AuthenticationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationParameters) DeepCopyInto(out *AuthenticationParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationParameters.
func (in *AuthenticationParameters) DeepCopy() *AuthenticationParameters {
	if in == nil {
		return nil
	}
	out := new(AuthenticationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTP) DeepCopyInto(out *ConfigHTTP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTP.
func (in *ConfigHTTP) DeepCopy() *ConfigHTTP {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigHTTP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPInitParameters) DeepCopyInto(out *ConfigHTTPInitParameters) {
	*out = *in
	if in.HTTPProxy != nil {
		in, out := &in.HTTPProxy, &out.HTTPProxy
		*out = new(HTTPProxyInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSProxy != nil {
		in, out := &in.HTTPSProxy, &out.HTTPSProxy
		*out = new(HTTPSProxyInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.NonProxyHosts != nil {
		in, out := &in.NonProxyHosts, &out.NonProxyHosts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.UserAgent != nil {
		in, out := &in.UserAgent, &out.UserAgent
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPInitParameters.
func (in *ConfigHTTPInitParameters) DeepCopy() *ConfigHTTPInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPList) DeepCopyInto(out *ConfigHTTPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigHTTP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPList.
func (in *ConfigHTTPList) DeepCopy() *ConfigHTTPList {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigHTTPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPObservation) DeepCopyInto(out *ConfigHTTPObservation) {
	*out = *in
	if in.HTTPProxy != nil {
		in, out := &in.HTTPProxy, &out.HTTPProxy
		*out = new(HTTPProxyObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSProxy != nil {
		in, out := &in.HTTPSProxy, &out.HTTPSProxy
		*out = new(HTTPSProxyObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.NonProxyHosts != nil {
		in, out := &in.NonProxyHosts, &out.NonProxyHosts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.UserAgent != nil {
		in, out := &in.UserAgent, &out.UserAgent
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPObservation.
func (in *ConfigHTTPObservation) DeepCopy() *ConfigHTTPObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPParameters) DeepCopyInto(out *ConfigHTTPParameters) {
	*out = *in
	if in.HTTPProxy != nil {
		in, out := &in.HTTPProxy, &out.HTTPProxy
		*out = new(HTTPProxyParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPSProxy != nil {
		in, out := &in.HTTPSProxy, &out.HTTPSProxy
		*out = new(HTTPSProxyParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.NonProxyHosts != nil {
		in, out := &in.NonProxyHosts, &out.NonProxyHosts
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Retries != nil {
		in, out := &in.Retries, &out.Retries
		*out = new(float64)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(float64)
		**out = **in
	}
	if in.UserAgent != nil {
		in, out := &in.UserAgent, &out.UserAgent
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPParameters.
func (in *ConfigHTTPParameters) DeepCopy() *ConfigHTTPParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPSpec) DeepCopyInto(out *ConfigHTTPSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPSpec.
func (in *ConfigHTTPSpec) DeepCopy() *ConfigHTTPSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigHTTPStatus) DeepCopyInto(out *ConfigHTTPStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigHTTPStatus.
func (in *ConfigHTTPStatus) DeepCopy() *ConfigHTTPStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigHTTPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnection) DeepCopyInto(out *ConfigLdapConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnection.
func (in *ConfigLdapConnection) DeepCopy() *ConfigLdapConnection {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigLdapConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionInitParameters) DeepCopyInto(out *ConfigLdapConnectionInitParameters) {
	*out = *in
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthScheme != nil {
		in, out := &in.AuthScheme, &out.AuthScheme
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelay != nil {
		in, out := &in.ConnectionRetryDelay, &out.ConnectionRetryDelay
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.MapLdapGroupsToRoles != nil {
		in, out := &in.MapLdapGroupsToRoles, &out.MapLdapGroupsToRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxConnectionAttempts != nil {
		in, out := &in.MaxConnectionAttempts, &out.MaxConnectionAttempts
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailNameAttribute != nil {
		in, out := &in.UserEmailNameAttribute, &out.UserEmailNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionInitParameters.
func (in *ConfigLdapConnectionInitParameters) DeepCopy() *ConfigLdapConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionList) DeepCopyInto(out *ConfigLdapConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigLdapConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionList.
func (in *ConfigLdapConnectionList) DeepCopy() *ConfigLdapConnectionList {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigLdapConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionObservation) DeepCopyInto(out *ConfigLdapConnectionObservation) {
	*out = *in
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthScheme != nil {
		in, out := &in.AuthScheme, &out.AuthScheme
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelay != nil {
		in, out := &in.ConnectionRetryDelay, &out.ConnectionRetryDelay
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.MapLdapGroupsToRoles != nil {
		in, out := &in.MapLdapGroupsToRoles, &out.MapLdapGroupsToRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxConnectionAttempts != nil {
		in, out := &in.MaxConnectionAttempts, &out.MaxConnectionAttempts
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailNameAttribute != nil {
		in, out := &in.UserEmailNameAttribute, &out.UserEmailNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionObservation.
func (in *ConfigLdapConnectionObservation) DeepCopy() *ConfigLdapConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionParameters) DeepCopyInto(out *ConfigLdapConnectionParameters) {
	*out = *in
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.AuthRealm != nil {
		in, out := &in.AuthRealm, &out.AuthRealm
		*out = new(string)
		**out = **in
	}
	if in.AuthScheme != nil {
		in, out := &in.AuthScheme, &out.AuthScheme
		*out = new(string)
		**out = **in
	}
	if in.AuthUsername != nil {
		in, out := &in.AuthUsername, &out.AuthUsername
		*out = new(string)
		**out = **in
	}
	if in.ConnectionRetryDelay != nil {
		in, out := &in.ConnectionRetryDelay, &out.ConnectionRetryDelay
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupIDAttribute != nil {
		in, out := &in.GroupIDAttribute, &out.GroupIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberFormat != nil {
		in, out := &in.GroupMemberFormat, &out.GroupMemberFormat
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectClass != nil {
		in, out := &in.GroupObjectClass, &out.GroupObjectClass
		*out = new(string)
		**out = **in
	}
	if in.GroupSubtree != nil {
		in, out := &in.GroupSubtree, &out.GroupSubtree
		*out = new(bool)
		**out = **in
	}
	if in.GroupType != nil {
		in, out := &in.GroupType, &out.GroupType
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.MapLdapGroupsToRoles != nil {
		in, out := &in.MapLdapGroupsToRoles, &out.MapLdapGroupsToRoles
		*out = new(bool)
		**out = **in
	}
	if in.MaxConnectionAttempts != nil {
		in, out := &in.MaxConnectionAttempts, &out.MaxConnectionAttempts
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.UserBaseDn != nil {
		in, out := &in.UserBaseDn, &out.UserBaseDn
		*out = new(string)
		**out = **in
	}
	if in.UserEmailNameAttribute != nil {
		in, out := &in.UserEmailNameAttribute, &out.UserEmailNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserIDAttribute != nil {
		in, out := &in.UserIDAttribute, &out.UserIDAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserLdapFilter != nil {
		in, out := &in.UserLdapFilter, &out.UserLdapFilter
		*out = new(string)
		**out = **in
	}
	if in.UserMemberOfAttribute != nil {
		in, out := &in.UserMemberOfAttribute, &out.UserMemberOfAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectClass != nil {
		in, out := &in.UserObjectClass, &out.UserObjectClass
		*out = new(string)
		**out = **in
	}
	if in.UserPasswordAttribute != nil {
		in, out := &in.UserPasswordAttribute, &out.UserPasswordAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserRealNameAttribute != nil {
		in, out := &in.UserRealNameAttribute, &out.UserRealNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserSubtree != nil {
		in, out := &in.UserSubtree, &out.UserSubtree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionParameters.
func (in *ConfigLdapConnectionParameters) DeepCopy() *ConfigLdapConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionSpec) DeepCopyInto(out *ConfigLdapConnectionSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionSpec.
func (in *ConfigLdapConnectionSpec) DeepCopy() *ConfigLdapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigLdapConnectionStatus) DeepCopyInto(out *ConfigLdapConnectionStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigLdapConnectionStatus.
func (in *ConfigLdapConnectionStatus) DeepCopy() *ConfigLdapConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigLdapConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMail) DeepCopyInto(out *ConfigMail) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMail.
func (in *ConfigMail) DeepCopy() *ConfigMail {
	if in == nil {
		return nil
	}
	out := new(ConfigMail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMail) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailInitParameters) DeepCopyInto(out *ConfigMailInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FromAddress != nil {
		in, out := &in.FromAddress, &out.FromAddress
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.SSLOnConnectEnabled != nil {
		in, out := &in.SSLOnConnectEnabled, &out.SSLOnConnectEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSLServerIdentityCheckEnabled != nil {
		in, out := &in.SSLServerIdentityCheckEnabled, &out.SSLServerIdentityCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSEnabled != nil {
		in, out := &in.StartTLSEnabled, &out.StartTLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSRequired != nil {
		in, out := &in.StartTLSRequired, &out.StartTLSRequired
		*out = new(bool)
		**out = **in
	}
	if in.SubjectPrefix != nil {
		in, out := &in.SubjectPrefix, &out.SubjectPrefix
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailInitParameters.
func (in *ConfigMailInitParameters) DeepCopy() *ConfigMailInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigMailInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailList) DeepCopyInto(out *ConfigMailList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigMail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailList.
func (in *ConfigMailList) DeepCopy() *ConfigMailList {
	if in == nil {
		return nil
	}
	out := new(ConfigMailList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMailList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailObservation) DeepCopyInto(out *ConfigMailObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FromAddress != nil {
		in, out := &in.FromAddress, &out.FromAddress
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.SSLOnConnectEnabled != nil {
		in, out := &in.SSLOnConnectEnabled, &out.SSLOnConnectEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSLServerIdentityCheckEnabled != nil {
		in, out := &in.SSLServerIdentityCheckEnabled, &out.SSLServerIdentityCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSEnabled != nil {
		in, out := &in.StartTLSEnabled, &out.StartTLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSRequired != nil {
		in, out := &in.StartTLSRequired, &out.StartTLSRequired
		*out = new(bool)
		**out = **in
	}
	if in.SubjectPrefix != nil {
		in, out := &in.SubjectPrefix, &out.SubjectPrefix
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailObservation.
func (in *ConfigMailObservation) DeepCopy() *ConfigMailObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigMailObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailParameters) DeepCopyInto(out *ConfigMailParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FromAddress != nil {
		in, out := &in.FromAddress, &out.FromAddress
		*out = new(string)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.SSLOnConnectEnabled != nil {
		in, out := &in.SSLOnConnectEnabled, &out.SSLOnConnectEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SSLServerIdentityCheckEnabled != nil {
		in, out := &in.SSLServerIdentityCheckEnabled, &out.SSLServerIdentityCheckEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSEnabled != nil {
		in, out := &in.StartTLSEnabled, &out.StartTLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StartTLSRequired != nil {
		in, out := &in.StartTLSRequired, &out.StartTLSRequired
		*out = new(bool)
		**out = **in
	}
	if in.SubjectPrefix != nil {
		in, out := &in.SubjectPrefix, &out.SubjectPrefix
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailParameters.
func (in *ConfigMailParameters) DeepCopy() *ConfigMailParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigMailParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailSpec) DeepCopyInto(out *ConfigMailSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailSpec.
func (in *ConfigMailSpec) DeepCopy() *ConfigMailSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMailStatus) DeepCopyInto(out *ConfigMailStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMailStatus.
func (in *ConfigMailStatus) DeepCopy() *ConfigMailStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigMailStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicense) DeepCopyInto(out *ConfigProductLicense) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicense.
func (in *ConfigProductLicense) DeepCopy() *ConfigProductLicense {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicense)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigProductLicense) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseInitParameters) DeepCopyInto(out *ConfigProductLicenseInitParameters) {
	*out = *in
	out.LicenseDataSecretRef = in.LicenseDataSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseInitParameters.
func (in *ConfigProductLicenseInitParameters) DeepCopy() *ConfigProductLicenseInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseList) DeepCopyInto(out *ConfigProductLicenseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigProductLicense, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseList.
func (in *ConfigProductLicenseList) DeepCopy() *ConfigProductLicenseList {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigProductLicenseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseObservation) DeepCopyInto(out *ConfigProductLicenseObservation) {
	*out = *in
	if in.ContactCompany != nil {
		in, out := &in.ContactCompany, &out.ContactCompany
		*out = new(string)
		**out = **in
	}
	if in.ContactEmail != nil {
		in, out := &in.ContactEmail, &out.ContactEmail
		*out = new(string)
		**out = **in
	}
	if in.ContactName != nil {
		in, out := &in.ContactName, &out.ContactName
		*out = new(string)
		**out = **in
	}
	if in.EffectiveDate != nil {
		in, out := &in.EffectiveDate, &out.EffectiveDate
		*out = new(string)
		**out = **in
	}
	if in.ExpirationDate != nil {
		in, out := &in.ExpirationDate, &out.ExpirationDate
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(string)
		**out = **in
	}
	if in.Fingerprint != nil {
		in, out := &in.Fingerprint, &out.Fingerprint
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.LicenseType != nil {
		in, out := &in.LicenseType, &out.LicenseType
		*out = new(string)
		**out = **in
	}
	if in.LicensedUsers != nil {
		in, out := &in.LicensedUsers, &out.LicensedUsers
		*out = new(string)
		**out = **in
	}
	if in.MaxRepoComponents != nil {
		in, out := &in.MaxRepoComponents, &out.MaxRepoComponents
		*out = new(float64)
		**out = **in
	}
	if in.MaxRepoRequests != nil {
		in, out := &in.MaxRepoRequests, &out.MaxRepoRequests
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseObservation.
func (in *ConfigProductLicenseObservation) DeepCopy() *ConfigProductLicenseObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseParameters) DeepCopyInto(out *ConfigProductLicenseParameters) {
	*out = *in
	out.LicenseDataSecretRef = in.LicenseDataSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseParameters.
func (in *ConfigProductLicenseParameters) DeepCopy() *ConfigProductLicenseParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseSpec) DeepCopyInto(out *ConfigProductLicenseSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	out.ForProvider = in.ForProvider
	out.InitProvider = in.InitProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseSpec.
func (in *ConfigProductLicenseSpec) DeepCopy() *ConfigProductLicenseSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProductLicenseStatus) DeepCopyInto(out *ConfigProductLicenseStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProductLicenseStatus.
func (in *ConfigProductLicenseStatus) DeepCopy() *ConfigProductLicenseStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigProductLicenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxyInitParameters) DeepCopyInto(out *HTTPProxyInitParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxyInitParameters.
func (in *HTTPProxyInitParameters) DeepCopy() *HTTPProxyInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPProxyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxyObservation) DeepCopyInto(out *HTTPProxyObservation) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxyObservation.
func (in *HTTPProxyObservation) DeepCopy() *HTTPProxyObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPProxyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxyParameters) DeepCopyInto(out *HTTPProxyParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxyParameters.
func (in *HTTPProxyParameters) DeepCopy() *HTTPProxyParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPProxyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyAuthenticationInitParameters) DeepCopyInto(out *HTTPSProxyAuthenticationInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyAuthenticationInitParameters.
func (in *HTTPSProxyAuthenticationInitParameters) DeepCopy() *HTTPSProxyAuthenticationInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyAuthenticationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyAuthenticationObservation) DeepCopyInto(out *HTTPSProxyAuthenticationObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyAuthenticationObservation.
func (in *HTTPSProxyAuthenticationObservation) DeepCopy() *HTTPSProxyAuthenticationObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyAuthenticationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyAuthenticationParameters) DeepCopyInto(out *HTTPSProxyAuthenticationParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NtlmDomain != nil {
		in, out := &in.NtlmDomain, &out.NtlmDomain
		*out = new(string)
		**out = **in
	}
	if in.NtlmHost != nil {
		in, out := &in.NtlmHost, &out.NtlmHost
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyAuthenticationParameters.
func (in *HTTPSProxyAuthenticationParameters) DeepCopy() *HTTPSProxyAuthenticationParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyAuthenticationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyInitParameters) DeepCopyInto(out *HTTPSProxyInitParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPSProxyAuthenticationInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyInitParameters.
func (in *HTTPSProxyInitParameters) DeepCopy() *HTTPSProxyInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyObservation) DeepCopyInto(out *HTTPSProxyObservation) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPSProxyAuthenticationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyObservation.
func (in *HTTPSProxyObservation) DeepCopy() *HTTPSProxyObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSProxyParameters) DeepCopyInto(out *HTTPSProxyParameters) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(HTTPSProxyAuthenticationParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSProxyParameters.
func (in *HTTPSProxyParameters) DeepCopy() *HTTPSProxyParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSProxyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnection) DeepCopyInto(out *IqConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnection.
func (in *IqConnection) DeepCopy() *IqConnection {
	if in == nil {
		return nil
	}
	out := new(IqConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IqConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionInitParameters) DeepCopyInto(out *IqConnectionInitParameters) {
	*out = *in
	if in.AuthenticationMethod != nil {
		in, out := &in.AuthenticationMethod, &out.AuthenticationMethod
		*out = new(string)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailOpenModeEnabled != nil {
		in, out := &in.FailOpenModeEnabled, &out.FailOpenModeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(string)
		**out = **in
	}
	if in.ShowIqServerLink != nil {
		in, out := &in.ShowIqServerLink, &out.ShowIqServerLink
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionInitParameters.
func (in *IqConnectionInitParameters) DeepCopy() *IqConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(IqConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionList) DeepCopyInto(out *IqConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IqConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionList.
func (in *IqConnectionList) DeepCopy() *IqConnectionList {
	if in == nil {
		return nil
	}
	out := new(IqConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IqConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionObservation) DeepCopyInto(out *IqConnectionObservation) {
	*out = *in
	if in.AuthenticationMethod != nil {
		in, out := &in.AuthenticationMethod, &out.AuthenticationMethod
		*out = new(string)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailOpenModeEnabled != nil {
		in, out := &in.FailOpenModeEnabled, &out.FailOpenModeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(string)
		**out = **in
	}
	if in.ShowIqServerLink != nil {
		in, out := &in.ShowIqServerLink, &out.ShowIqServerLink
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionObservation.
func (in *IqConnectionObservation) DeepCopy() *IqConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(IqConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionParameters) DeepCopyInto(out *IqConnectionParameters) {
	*out = *in
	if in.AuthenticationMethod != nil {
		in, out := &in.AuthenticationMethod, &out.AuthenticationMethod
		*out = new(string)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailOpenModeEnabled != nil {
		in, out := &in.FailOpenModeEnabled, &out.FailOpenModeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NexusTrustStoreEnabled != nil {
		in, out := &in.NexusTrustStoreEnabled, &out.NexusTrustStoreEnabled
		*out = new(bool)
		**out = **in
	}
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(string)
		**out = **in
	}
	if in.ShowIqServerLink != nil {
		in, out := &in.ShowIqServerLink, &out.ShowIqServerLink
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionParameters.
func (in *IqConnectionParameters) DeepCopy() *IqConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(IqConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionSpec) DeepCopyInto(out *IqConnectionSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionSpec.
func (in *IqConnectionSpec) DeepCopy() *IqConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(IqConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IqConnectionStatus) DeepCopyInto(out *IqConnectionStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IqConnectionStatus.
func (in *IqConnectionStatus) DeepCopy() *IqConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(IqConnectionStatus)
	in.DeepCopyInto(out)
	return out
}
