// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type IqConnectionInitParameters struct {

	// Authentication method for Sonatype IQ Connection
	AuthenticationMethod *string `json:"authenticationMethod,omitempty" tf:"authentication_method,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection.
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// Whether to use Sonatype Repository Firewall
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Allow by default when quarantine is enabled and the connection to Sonatype IQ Server fails
	FailOpenModeEnabled *bool `json:"failOpenModeEnabled,omitempty" tf:"fail_open_mode_enabled,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to Sonatype IQ Server
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// Credentials for the Sonatype Repository Firewall User
	PasswordSecretRef v2.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// Additional properties to configure for Sonatype Repository Firewall
	Properties *string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Show Sonatype Repository Firewall link in Browse menu when server is enabled
	ShowIqServerLink *bool `json:"showIqServerLink,omitempty" tf:"show_iq_server_link,omitempty"`

	// The address of your Sonatype IQ Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User with access to Sonatype Repository Firewall
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type IqConnectionObservation struct {

	// Authentication method for Sonatype IQ Connection
	AuthenticationMethod *string `json:"authenticationMethod,omitempty" tf:"authentication_method,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection.
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// Whether to use Sonatype Repository Firewall
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Allow by default when quarantine is enabled and the connection to Sonatype IQ Server fails
	FailOpenModeEnabled *bool `json:"failOpenModeEnabled,omitempty" tf:"fail_open_mode_enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to Sonatype IQ Server
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// Additional properties to configure for Sonatype Repository Firewall
	Properties *string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Show Sonatype Repository Firewall link in Browse menu when server is enabled
	ShowIqServerLink *bool `json:"showIqServerLink,omitempty" tf:"show_iq_server_link,omitempty"`

	// The address of your Sonatype IQ Server
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User with access to Sonatype Repository Firewall
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type IqConnectionParameters struct {

	// Authentication method for Sonatype IQ Connection
	// +kubebuilder:validation:Optional
	AuthenticationMethod *string `json:"authenticationMethod,omitempty" tf:"authentication_method,omitempty"`

	// Seconds to wait for activity before stopping and retrying the connection.
	// +kubebuilder:validation:Optional
	ConnectionTimeout *float64 `json:"connectionTimeout,omitempty" tf:"connection_timeout,omitempty"`

	// Whether to use Sonatype Repository Firewall
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Allow by default when quarantine is enabled and the connection to Sonatype IQ Server fails
	// +kubebuilder:validation:Optional
	FailOpenModeEnabled *bool `json:"failOpenModeEnabled,omitempty" tf:"fail_open_mode_enabled,omitempty"`

	// Use certificates stored in the Nexus Repository Manager truststore to connect to Sonatype IQ Server
	// +kubebuilder:validation:Optional
	NexusTrustStoreEnabled *bool `json:"nexusTrustStoreEnabled,omitempty" tf:"nexus_trust_store_enabled,omitempty"`

	// Credentials for the Sonatype Repository Firewall User
	// +kubebuilder:validation:Optional
	PasswordSecretRef v2.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// Additional properties to configure for Sonatype Repository Firewall
	// +kubebuilder:validation:Optional
	Properties *string `json:"properties,omitempty" tf:"properties,omitempty"`

	// Show Sonatype Repository Firewall link in Browse menu when server is enabled
	// +kubebuilder:validation:Optional
	ShowIqServerLink *bool `json:"showIqServerLink,omitempty" tf:"show_iq_server_link,omitempty"`

	// The address of your Sonatype IQ Server
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// User with access to Sonatype Repository Firewall
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// IqConnectionSpec defines the desired state of IqConnection
type IqConnectionSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   IqConnectionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IqConnectionInitParameters `json:"initProvider,omitempty"`
}

// IqConnectionStatus defines the observed state of IqConnection.
type IqConnectionStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               IqConnectionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IqConnection is the Schema for the IqConnections API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type IqConnection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authenticationMethod) || (has(self.initProvider) && has(self.initProvider.authenticationMethod))",message="spec.forProvider.authenticationMethod is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.failOpenModeEnabled) || (has(self.initProvider) && has(self.initProvider.failOpenModeEnabled))",message="spec.forProvider.failOpenModeEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nexusTrustStoreEnabled) || (has(self.initProvider) && has(self.initProvider.nexusTrustStoreEnabled))",message="spec.forProvider.nexusTrustStoreEnabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.showIqServerLink) || (has(self.initProvider) && has(self.initProvider.showIqServerLink))",message="spec.forProvider.showIqServerLink is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   IqConnectionSpec   `json:"spec"`
	Status IqConnectionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IqConnectionList contains a list of IqConnections
type IqConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IqConnection `json:"items"`
}

// Repository type metadata.
var (
	IqConnection_Kind             = "IqConnection"
	IqConnection_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IqConnection_Kind}.String()
	IqConnection_KindAPIVersion   = IqConnection_Kind + "." + CRDGroupVersion.String()
	IqConnection_GroupVersionKind = CRDGroupVersion.WithKind(IqConnection_Kind)
)

func init() {
	SchemeBuilder.Register(&IqConnection{}, &IqConnectionList{})
}
