apiVersion: task.nexus.m.tinyorbit.vn/v1alpha1
kind: LicenseExpirationNotification
metadata:
  annotations:
    meta.upbound.io/example-id: task/v1alpha1/licenseexpirationnotification
  labels:
    testing.upbound.io/example-name: task
  name: task
  namespace: crossplane-system
spec:
  forProvider:
    alertEmail: notifications@somewhere.tld
    enabled: true
    frequency:
      schedule: manual
    name: my-notifciation
    notificationCondition: FAILURE
