// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RepositoryContentSelectorInitParameters struct {

	// (Set of String) A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String) The name of a content selector that will be used to grant access to content via this privilege.
	// The name of a content selector that will be used to grant access to content via this privilege.
	ContentSelector *string `json:"contentSelector,omitempty" tf:"content_selector,omitempty"`

	// (String) Friendly description of this Privilege
	// Friendly description of this Privilege
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	// The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) The name of the repository this privilege will grant access to (or * for all).
	// The name of the repository this privilege will grant access to (or * for all).
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

type RepositoryContentSelectorObservation struct {

	// (Set of String) A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String) The name of a content selector that will be used to grant access to content via this privilege.
	// The name of a content selector that will be used to grant access to content via this privilege.
	ContentSelector *string `json:"contentSelector,omitempty" tf:"content_selector,omitempty"`

	// (String) Friendly description of this Privilege
	// Friendly description of this Privilege
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	// The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) String representation of the date/time the resource was last changed
	// String representation of the date/time the resource was last changed
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (Boolean) Indicates whether the privilege can be changed. External values supplied to this will be ignored by the system.
	// Indicates whether the privilege can be changed. External values supplied to this will be ignored by the system.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (String) The name of the repository this privilege will grant access to (or * for all).
	// The name of the repository this privilege will grant access to (or * for all).
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`

	// (String) The type of privilege, each type covers different portions of the system. External values supplied to this will be ignored by the system.
	// The type of privilege, each type covers different portions of the system. External values supplied to this will be ignored by the system.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RepositoryContentSelectorParameters struct {

	// (Set of String) A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// A set of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String) The name of a content selector that will be used to grant access to content via this privilege.
	// The name of a content selector that will be used to grant access to content via this privilege.
	// +kubebuilder:validation:Optional
	ContentSelector *string `json:"contentSelector,omitempty" tf:"content_selector,omitempty"`

	// (String) Friendly description of this Privilege
	// Friendly description of this Privilege
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	// The repository format (i.e 'nuget', 'npm') this privilege will grant access to (or * for all).
	// +kubebuilder:validation:Optional
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) The name of the repository this privilege will grant access to (or * for all).
	// The name of the repository this privilege will grant access to (or * for all).
	// +kubebuilder:validation:Optional
	Repository *string `json:"repository,omitempty" tf:"repository,omitempty"`
}

// RepositoryContentSelectorSpec defines the desired state of RepositoryContentSelector
type RepositoryContentSelectorSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RepositoryContentSelectorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryContentSelectorInitParameters `json:"initProvider,omitempty"`
}

// RepositoryContentSelectorStatus defines the observed state of RepositoryContentSelector.
type RepositoryContentSelectorStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RepositoryContentSelectorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RepositoryContentSelector is the Schema for the RepositoryContentSelectors API. Manage a Privilege of type repository-content-selector
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sonatyperepo}
type RepositoryContentSelector struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.actions) || (has(self.initProvider) && has(self.initProvider.actions))",message="spec.forProvider.actions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contentSelector) || (has(self.initProvider) && has(self.initProvider.contentSelector))",message="spec.forProvider.contentSelector is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.format) || (has(self.initProvider) && has(self.initProvider.format))",message="spec.forProvider.format is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.repository) || (has(self.initProvider) && has(self.initProvider.repository))",message="spec.forProvider.repository is a required parameter"
	Spec   RepositoryContentSelectorSpec   `json:"spec"`
	Status RepositoryContentSelectorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryContentSelectorList contains a list of RepositoryContentSelectors
type RepositoryContentSelectorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RepositoryContentSelector `json:"items"`
}

// Repository type metadata.
var (
	RepositoryContentSelector_Kind             = "RepositoryContentSelector"
	RepositoryContentSelector_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RepositoryContentSelector_Kind}.String()
	RepositoryContentSelector_KindAPIVersion   = RepositoryContentSelector_Kind + "." + CRDGroupVersion.String()
	RepositoryContentSelector_GroupVersionKind = CRDGroupVersion.WithKind(RepositoryContentSelector_Kind)
)

func init() {
	SchemeBuilder.Register(&RepositoryContentSelector{}, &RepositoryContentSelectorList{})
}
