apiVersion: blobstore.nexus.tinyorbit.vn/v1alpha1
kind: S3
metadata:
  annotations:
    meta.upbound.io/example-id: blobstore/v1alpha1/s3
  labels:
    testing.upbound.io/example-name: s3_blob_store
  name: s3-blob-store
spec:
  forProvider:
    advanced_bucket_connection:
      chunked_encoding: false
      endpoint: https://s3.us-east-1.amazonaws.com
      path_style_access: false
      signature_version: AWSSIGV4
    bucket_security:
      access_key_id: AKIAIOSFODNN7EXAMPLE
      secret_access_key: SECRET_EXAMPLE
    bucketConfiguration:
      bucket: my-nexus-bucket
      prefix: nexus
      region: us-east-1
    encryption:
      encryption_type: s3
