apiVersion: security.nexus.m.tinyorbit.vn/v1alpha1
kind: Realms
metadata:
  name: realms
  namespace: nexus
  annotations:
    crossplane.io/external-name: SECURITY_REALMS
spec:
  managementPolicies: ["Observe"]
  providerConfigRef: { name: default, kind: ProviderConfig }
  forProvider: {}
---
apiVersion: system.nexus.m.tinyorbit.vn/v1alpha1
kind: AnonymousAccess
metadata:
  name: anonymous
  namespace: nexus
  annotations:
    crossplane.io/external-name: ANONYMOUS_ACCESS
spec:
  managementPolicies: ["Observe"]
  providerConfigRef: { name: default, kind: ProviderConfig }
  forProvider: {}
---
apiVersion: security.nexus.m.tinyorbit.vn/v1alpha1
kind: SsrfProtection
metadata:
  name: ssrf
  namespace: nexus
  annotations:
    crossplane.io/external-name: SSRF_PROTECTION
spec:
  managementPolicies: ["Observe"]
  providerConfigRef: { name: default, kind: ProviderConfig }
  forProvider: {}
