apiVersion: capability.nexus.m.tinyorbit.vn/v1alpha1
kind: WebhookGlobal
metadata:
  annotations:
    meta.upbound.io/example-id: capability/v1alpha1/webhookglobal
  labels:
    testing.upbound.io/example-name: webhook_global
  name: webhook-global
  namespace: crossplane-system
spec:
  forProvider:
    enabled: true
    notes: Global webhook configuration
    properties:
      names:
      - repository
      secretSecretRef:
        key: example-key
        name: example-secret
      url: https://webhook.example.com/receive
